# Form implementation generated from reading ui file '边框重写.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        Form.setMouseTracking(True)
        self.MustLayout = QtWidgets.QVBoxLayout(Form)
        self.MustLayout.setContentsMargins(0, 0, 0, 0)
        self.MustLayout.setSpacing(0)
        self.MustLayout.setObjectName("MustLayout")
        self.GlobalWidget = QtWidgets.QWidget(parent=Form)
        self.GlobalWidget.setMouseTracking(True)
        self.GlobalWidget.setObjectName("GlobalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.GlobalWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleBar = QtWidgets.QGridLayout()
        self.TitleBar.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.TitleBar.setSpacing(0)
        self.TitleBar.setObjectName("TitleBar")
        self.TitleLayout = QtWidgets.QHBoxLayout()
        self.TitleLayout.setContentsMargins(5, 5, 0, -1)
        self.TitleLayout.setSpacing(0)
        self.TitleLayout.setObjectName("TitleLayout")
        self.LabelPic = QtWidgets.QLabel(parent=self.GlobalWidget)
        self.LabelPic.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.LabelPic.setText("")
        self.LabelPic.setPixmap(QtGui.QPixmap("32X32.ico"))
        self.LabelPic.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.LabelPic.setObjectName("LabelPic")
        self.TitleLayout.addWidget(self.LabelPic)
        self.SoftwareName = QtWidgets.QLabel(parent=self.GlobalWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.SoftwareName.setFont(font)
        self.SoftwareName.setObjectName("SoftwareName")
        self.TitleLayout.addWidget(self.SoftwareName)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.TitleLayout.addItem(spacerItem)
        self.TitleLayout.setStretch(2, 13)
        self.TitleBar.addLayout(self.TitleLayout, 0, 0, 2, 1)
        self.WindowControlButtons = QtWidgets.QHBoxLayout()
        self.WindowControlButtons.setSpacing(0)
        self.WindowControlButtons.setObjectName("WindowControlButtons")
        self.HideToWindow = QtWidgets.QPushButton(parent=self.GlobalWidget)
        self.HideToWindow.setMouseTracking(True)
        self.HideToWindow.setWhatsThis("")
        self.HideToWindow.setStyleSheet("QPushButton {\n"
"    background: transparent;  /* 透明背景 */\n"
"    border: none;            /* 移除默认边框 */\n"
"}\n"
"/* 悬停状态 */\n"
"QPushButton:hover {\n"
"    background: rgb(196, 43, 28); /* 轻微高亮 */\n"
"}\n"
"/* 按下状态 */\n"
"QPushButton:pressed {\n"
"    background: rgb(199, 64, 49);\n"
"}")
        self.HideToWindow.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("chevron-down.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.HideToWindow.setIcon(icon)
        self.HideToWindow.setIconSize(QtCore.QSize(40, 30))
        self.HideToWindow.setObjectName("HideToWindow")
        self.WindowControlButtons.addWidget(self.HideToWindow)
        self.MinToSys = QtWidgets.QPushButton(parent=self.GlobalWidget)
        self.MinToSys.setMouseTracking(True)
        self.MinToSys.setStatusTip("")
        self.MinToSys.setStyleSheet("QPushButton {\n"
"    background: transparent;  /* 透明背景 */\n"
"    border: none;            /* 移除默认边框 */\n"
"}\n"
"/* 悬停状态 */\n"
"QPushButton:hover {\n"
"    background: rgb(233, 233, 233); /* 轻微高亮 */\n"
"}\n"
"/* 按下状态 */\n"
"QPushButton:pressed {\n"
"    background: rgb(213, 213, 213);\n"
"}")
        self.MinToSys.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("chevrons-down.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.MinToSys.setIcon(icon1)
        self.MinToSys.setIconSize(QtCore.QSize(40, 30))
        self.MinToSys.setObjectName("MinToSys")
        self.WindowControlButtons.addWidget(self.MinToSys)
        self.Min = QtWidgets.QPushButton(parent=self.GlobalWidget)
        self.Min.setMouseTracking(True)
        self.Min.setStyleSheet("QPushButton {\n"
"    background: transparent;  /* 透明背景 */\n"
"    border: none;            /* 移除默认边框 */\n"
"}\n"
"/* 悬停状态 */\n"
"QPushButton:hover {\n"
"    background: rgb(233, 233, 233); /* 轻微高亮 */\n"
"}\n"
"/* 按下状态 */\n"
"QPushButton:pressed {\n"
"    background: rgb(213, 213, 213);\n"
"}")
        self.Min.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("remove.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Min.setIcon(icon2)
        self.Min.setIconSize(QtCore.QSize(40, 30))
        self.Min.setObjectName("Min")
        self.WindowControlButtons.addWidget(self.Min)
        self.MaxOrRestore = QtWidgets.QPushButton(parent=self.GlobalWidget)
        self.MaxOrRestore.setMouseTracking(True)
        self.MaxOrRestore.setStyleSheet("QPushButton {\n"
"    background: transparent;  /* 透明背景 */\n"
"    border: none;            /* 移除默认边框 */\n"
"}\n"
"/* 悬停状态 */\n"
"QPushButton:hover {\n"
"    background: rgb(233, 233, 233); /* 轻微高亮 */\n"
"}\n"
"/* 按下状态 */\n"
"QPushButton:pressed {\n"
"    background: rgb(213, 213, 213);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("maximise.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.MaxOrRestore.setIcon(icon3)
        self.MaxOrRestore.setIconSize(QtCore.QSize(40, 30))
        self.MaxOrRestore.setAutoRepeat(False)
        self.MaxOrRestore.setObjectName("MaxOrRestore")
        self.WindowControlButtons.addWidget(self.MaxOrRestore)
        self.Close = QtWidgets.QPushButton(parent=self.GlobalWidget)
        self.Close.setMouseTracking(True)
        self.Close.setStyleSheet("QPushButton {\n"
"    background: transparent;  /* 透明背景 */\n"
"    border:  transparent;            /* 移除默认边框 */\n"
"}\n"
"/* 悬停状态 */\n"
"QPushButton:hover {\n"
"    background: rgb(196, 43, 28); /* 轻微高亮 */\n"
"}\n"
"/* 按下状态 */\n"
"QPushButton:pressed {\n"
"    background: rgb(199, 64, 49);\n"
"}\n"
"")
        self.Close.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("cancel.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Close.setIcon(icon4)
        self.Close.setIconSize(QtCore.QSize(40, 30))
        self.Close.setObjectName("Close")
        self.WindowControlButtons.addWidget(self.Close)
        self.TitleBar.addLayout(self.WindowControlButtons, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.TitleBar)
        self.MainWidget = QtWidgets.QWidget(parent=self.GlobalWidget)
        self.MainWidget.setMouseTracking(True)
        self.MainWidget.setObjectName("MainWidget")
        self.verticalLayout.addWidget(self.MainWidget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 17)
        self.MustLayout.addWidget(self.GlobalWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SoftwareName.setText(_translate("Form", "Free my WW 1.0.0"))
        self.HideToWindow.setToolTip(_translate("Form", "完全隐藏（去任务管理器找）"))
        self.MinToSys.setToolTip(_translate("Form", "系统托盘"))
        self.Min.setToolTip(_translate("Form", "最小化"))
        self.MaxOrRestore.setToolTip(_translate("Form", "最大化/恢复"))
        self.Close.setToolTip(_translate("Form", "关闭"))
