# Form implementation generated from reading ui file 'B:\爱丽丝QQ聊天AI项目\爱丽丝QQ聊天AI\resources\Arisu.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Arisu(object):
    def setupUi(self, Arisu):
        Arisu.setObjectName("Arisu")
        Arisu.setEnabled(True)
        Arisu.resize(1280, 719)
        Arisu.setMouseTracking(False)
        Arisu.setAcceptDrops(False)
        Arisu.setAutoFillBackground(False)
        Arisu.setStyleSheet("background-color: rgb(240, 244, 249);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Arisu)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleBar = QtWidgets.QGridLayout()
        self.TitleBar.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.TitleBar.setContentsMargins(0, -1, -1, -1)
        self.TitleBar.setSpacing(0)
        self.TitleBar.setObjectName("TitleBar")
        self.TitleLayout = QtWidgets.QHBoxLayout()
        self.TitleLayout.setContentsMargins(5, 5, 0, 5)
        self.TitleLayout.setSpacing(5)
        self.TitleLayout.setObjectName("TitleLayout")
        self.Logo = QtWidgets.QLabel(parent=Arisu)
        self.Logo.setMouseTracking(False)
        self.Logo.setTabletTracking(False)
        self.Logo.setAcceptDrops(False)
        self.Logo.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap(":/Logo/Logo/32.ico"))
        self.Logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Logo.setObjectName("Logo")
        self.TitleLayout.addWidget(self.Logo)
        self.SoftwareName = QtWidgets.QLabel(parent=Arisu)
        self.SoftwareName.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.SoftwareName.setFont(font)
        self.SoftwareName.setMouseTracking(False)
        self.SoftwareName.setTabletTracking(False)
        self.SoftwareName.setAutoFillBackground(False)
        self.SoftwareName.setWordWrap(False)
        self.SoftwareName.setObjectName("SoftwareName")
        self.TitleLayout.addWidget(self.SoftwareName)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.TitleLayout.addItem(spacerItem)
        self.TitleBar.addLayout(self.TitleLayout, 0, 0, 2, 1)
        self.WindowControlButtons = QtWidgets.QHBoxLayout()
        self.WindowControlButtons.setSpacing(0)
        self.WindowControlButtons.setObjectName("WindowControlButtons")
        self.hide_btn = QtWidgets.QPushButton(parent=Arisu)
        self.hide_btn.setMouseTracking(True)
        self.hide_btn.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.hide_btn.setWhatsThis("")
        self.hide_btn.setStyleSheet("QPushButton {\n"
"    background: transparent;  /* 透明背景 */\n"
"    border: none;            /* 移除默认边框 */\n"
"}\n"
"/* 悬停状态 */\n"
"QPushButton:hover {\n"
"    background: rgb(233, 233, 233); /* 轻微高亮 */\n"
"}\n"
"/* 按下状态 */\n"
"QPushButton:pressed {\n"
"    background: rgb(213, 213, 213);\n"
"}")
        self.hide_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/标题栏/标题栏/深度隐藏.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.hide_btn.setIcon(icon)
        self.hide_btn.setIconSize(QtCore.QSize(40, 30))
        self.hide_btn.setObjectName("hide_btn")
        self.WindowControlButtons.addWidget(self.hide_btn)
        self.min_system_tray_btn = QtWidgets.QPushButton(parent=Arisu)
        self.min_system_tray_btn.setMouseTracking(True)
        self.min_system_tray_btn.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.min_system_tray_btn.setStyleSheet("QPushButton {\n"
"    background: transparent;  /* 透明背景 */\n"
"    border:  transparent;            /* 移除默认边框 */\n"
"}\n"
"/* 悬停状态 */\n"
"QPushButton:hover {\n"
"    background: rgb(233, 233, 233); /* 轻微高亮 */\n"
"}\n"
"/* 按下状态 */\n"
"QPushButton:pressed {\n"
"    background: rgb(213, 213, 213);\n"
"}")
        self.min_system_tray_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/标题栏/标题栏/托盘隐藏.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.min_system_tray_btn.setIcon(icon1)
        self.min_system_tray_btn.setIconSize(QtCore.QSize(40, 30))
        self.min_system_tray_btn.setObjectName("min_system_tray_btn")
        self.WindowControlButtons.addWidget(self.min_system_tray_btn)
        self.top_btn = QtWidgets.QPushButton(parent=Arisu)
        self.top_btn.setMouseTracking(True)
        self.top_btn.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.top_btn.setStyleSheet("QPushButton {\n"
"    background: transparent;  /* 透明背景 */\n"
"    border:  transparent;            /* 移除默认边框 */\n"
"}\n"
"/* 悬停状态 */\n"
"QPushButton:hover {\n"
"    background: rgb(233, 233, 233); /* 轻微高亮 */\n"
"}\n"
"/* 按下状态 */\n"
"QPushButton:pressed {\n"
"    background: rgb(213, 213, 213);\n"
"}")
        self.top_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/标题栏/标题栏/窗口置顶.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.top_btn.setIcon(icon2)
        self.top_btn.setIconSize(QtCore.QSize(40, 30))
        self.top_btn.setObjectName("top_btn")
        self.WindowControlButtons.addWidget(self.top_btn)
        self.min_btn = QtWidgets.QPushButton(parent=Arisu)
        self.min_btn.setMouseTracking(True)
        self.min_btn.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.min_btn.setStyleSheet("QPushButton {\n"
"    background: transparent;  /* 透明背景 */\n"
"    border: none;            /* 移除默认边框 */\n"
"}\n"
"/* 悬停状态 */\n"
"QPushButton:hover {\n"
"    background: rgb(233, 233, 233); /* 轻微高亮 */\n"
"}\n"
"/* 按下状态 */\n"
"QPushButton:pressed {\n"
"    background: rgb(213, 213, 213);\n"
"}")
        self.min_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/标题栏/标题栏/最小化.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.min_btn.setIcon(icon3)
        self.min_btn.setIconSize(QtCore.QSize(40, 30))
        self.min_btn.setObjectName("min_btn")
        self.WindowControlButtons.addWidget(self.min_btn)
        self.max_btn = QtWidgets.QPushButton(parent=Arisu)
        self.max_btn.setMouseTracking(True)
        self.max_btn.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.max_btn.setStyleSheet("QPushButton {\n"
"    background: transparent;  /* 透明背景 */\n"
"    border: none;            /* 移除默认边框 */\n"
"}\n"
"/* 悬停状态 */\n"
"QPushButton:hover {\n"
"    background: rgb(233, 233, 233); /* 轻微高亮 */\n"
"}\n"
"/* 按下状态 */\n"
"QPushButton:pressed {\n"
"    background: rgb(213, 213, 213);\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/标题栏/标题栏/最大化.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.max_btn.setIcon(icon4)
        self.max_btn.setIconSize(QtCore.QSize(40, 30))
        self.max_btn.setCheckable(True)
        self.max_btn.setChecked(False)
        self.max_btn.setAutoRepeat(False)
        self.max_btn.setObjectName("max_btn")
        self.WindowControlButtons.addWidget(self.max_btn)
        self.close_btn = QtWidgets.QPushButton(parent=Arisu)
        self.close_btn.setMouseTracking(True)
        self.close_btn.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.close_btn.setStyleSheet("QPushButton {\n"
"    background: transparent;  /* 透明背景 */\n"
"    border:  transparent;            /* 移除默认边框 */\n"
"}\n"
"/* 悬停状态 */\n"
"QPushButton:hover {\n"
"    background: rgb(196, 43, 28); /* 轻微高亮 */\n"
"}\n"
"/* 按下状态 */\n"
"QPushButton:pressed {\n"
"    background: rgb(199, 64, 49);\n"
"}\n"
"")
        self.close_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/标题栏/标题栏/关闭.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close_btn.setIcon(icon5)
        self.close_btn.setIconSize(QtCore.QSize(40, 30))
        self.close_btn.setObjectName("close_btn")
        self.WindowControlButtons.addWidget(self.close_btn)
        self.TitleBar.addLayout(self.WindowControlButtons, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.TitleBar)
        self.ModeWidget = QtWidgets.QTabWidget(parent=Arisu)
        self.ModeWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.ModeWidget.setMouseTracking(False)
        self.ModeWidget.setTabletTracking(False)
        self.ModeWidget.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.ModeWidget.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        self.ModeWidget.setAcceptDrops(False)
        self.ModeWidget.setToolTip("")
        self.ModeWidget.setWhatsThis("")
        self.ModeWidget.setAutoFillBackground(False)
        self.ModeWidget.setStyleSheet("/* 设置选项卡最小/最大尺寸 */\n"
"QTabBar::tab {\n"
"    border-right:  1px solid rgb(226, 230, 234);  /* 右边框显示颜色 */\n"
"    border-top-left-radius: 10px;    /* 左上角圆角半径 */\n"
"    border-bottom-right-radius: 0px; /* 右下角直角 */\n"
"    min-width: 70px;  /* 最小宽度 */\n"
"    min-height: 50px;  /* 最小高度 */\n"
"\n"
"}\n"
"\n"
"/* 悬停状态 */\n"
"QTabBar::tab:hover {\n"
"    background:rgb(85, 255, 255);\n"
"    border-radius: 10px;        /*圆角*/\n"
"}\n"
"\n"
"/* 选中状态 */\n"
"QTabBar::tab:selected {\n"
"    border-top-right-radius: 0px;   /* 右上角圆角半径 */\n"
"    border-bottom-left-radius: 0px;  /* 左下角直角 */\n"
"    border-bottom-right-radius: 0px; /* 右下角直角 */\n"
"    background-color: rgba(85, 255, 255,0.3);        /*背景颜色*/\n"
"   color: white;             /* 选中文字色 */\n"
"   border-bottom: 10px solid rgb(85, 255, 255); /* 底部指示条 */\n"
"}")
        self.ModeWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.West)
        self.ModeWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.ModeWidget.setIconSize(QtCore.QSize(40, 40))
        self.ModeWidget.setUsesScrollButtons(False)
        self.ModeWidget.setDocumentMode(False)
        self.ModeWidget.setTabsClosable(False)
        self.ModeWidget.setMovable(True)
        self.ModeWidget.setTabBarAutoHide(False)
        self.ModeWidget.setObjectName("ModeWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Home)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.DynamicBackground = QVideoWidget(parent=self.Home)
        self.DynamicBackground.setStyleSheet("QWidget {\n"
"    border-radius: 10px;        /*圆角*/\n"
"    border: none;\n"
"    background-color: rgba(170, 255, 255,0.3);    /*加个背景颜色*/\n"
"}\n"
"")
        self.DynamicBackground.setObjectName("DynamicBackground")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.DynamicBackground)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3.addWidget(self.DynamicBackground)
        self.HomeButton = QtWidgets.QWidget(parent=self.Home)
        self.HomeButton.setStyleSheet("QWidget {\n"
"    border-radius: 10px;        /*圆角*/    \n"
"    background-color: rgb(255, 255, 255);\n"
"    text-align : bottom;    /*文本放在底层*/\n"
"}")
        self.HomeButton.setObjectName("HomeButton")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.HomeButton)
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Function1 = QtWidgets.QToolButton(parent=self.HomeButton)
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(20)
        self.Function1.setFont(font)
        self.Function1.setStyleSheet("QToolButton {\n"
"    background-color: rgb(0, 255, 255);    /*设置背景颜色*/\n"
"    color: rgb(65, 65, 220); /* 设置所有按钮字体为蓝色 */\n"
"    padding-top: 10px;        /*调整内部距离*/\n"
"    padding-left: 10px;        /*调整内部距离*/\n"
"    padding-right: 10px;        /*调整内部距离*/\n"
"    padding-bottom: 10px;    /*调整内部距离*/\n"
"    border: 5px double rgb(65, 65, 220);  /*边框大小、双边框、边框颜色*/\n"
"}\n"
"\n"
"/* ===== 悬停效果 ===== */\n"
"QToolButton:hover {\n"
"    background-color: rgba(0, 255, 255, 0.5);\n"
"    color: rgba(65, 65, 220, 0.5); /* 设置所有按钮字体为蓝色 */    \n"
"}\n"
"\n"
"/* ===== 按下效果 ===== */\n"
"QToolButton:pressed {\n"
"    background-color: rgb(0, 255, 255);\n"
"    color: rgb(255,255,255);\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/爱丽丝表情包/爱丽丝表情包/女仆/1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Function1.setIcon(icon6)
        self.Function1.setIconSize(QtCore.QSize(100, 100))
        self.Function1.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.Function1.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.Function1.setAutoRaise(False)
        self.Function1.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.Function1.setObjectName("Function1")
        self.horizontalLayout.addWidget(self.Function1)
        self.Function2 = QtWidgets.QToolButton(parent=self.HomeButton)
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(20)
        self.Function2.setFont(font)
        self.Function2.setStyleSheet("QToolButton {\n"
"    background-color: rgb(0, 255, 255);    /*设置背景颜色*/\n"
"    color: rgb(65, 65, 220); /* 设置所有按钮字体为蓝色 */\n"
"    padding-top: 10px;        /*调整内部距离*/\n"
"    padding-left: 10px;        /*调整内部距离*/\n"
"    padding-right: 10px;        /*调整内部距离*/\n"
"    padding-bottom: 10px;    /*调整内部距离*/\n"
"    border: 5px double rgb(65, 65, 220);  /*边框大小、双边框、边框颜色*/\n"
"}\n"
"\n"
"/* ===== 悬停效果 ===== */\n"
"QToolButton:hover {\n"
"    background-color: rgba(0, 255, 255, 0.5);\n"
"    color: rgba(65, 65, 220, 0.5); /* 设置所有按钮字体为蓝色 */    \n"
"}\n"
"\n"
"/* ===== 按下效果 ===== */\n"
"QToolButton:pressed {\n"
"    background-color: rgb(0, 255, 255);\n"
"    color: rgb(255,255,255);\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/爱丽丝表情包/爱丽丝表情包/非女仆/2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Function2.setIcon(icon7)
        self.Function2.setIconSize(QtCore.QSize(100, 100))
        self.Function2.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.Function2.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.Function2.setAutoRaise(False)
        self.Function2.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.Function2.setObjectName("Function2")
        self.horizontalLayout.addWidget(self.Function2)
        self.Function3 = QtWidgets.QToolButton(parent=self.HomeButton)
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(20)
        self.Function3.setFont(font)
        self.Function3.setStyleSheet("QToolButton {\n"
"    background-color: rgb(0, 255, 255);    /*设置背景颜色*/\n"
"    color: rgb(65, 65, 220); /* 设置所有按钮字体为蓝色 */\n"
"    padding-top: 10px;        /*调整内部距离*/\n"
"    padding-left: 10px;        /*调整内部距离*/\n"
"    padding-right: 10px;        /*调整内部距离*/\n"
"    padding-bottom: 10px;    /*调整内部距离*/\n"
"    border: 5px double rgb(65, 65, 220);  /*边框大小、双边框、边框颜色*/\n"
"}\n"
"\n"
"/* ===== 悬停效果 ===== */\n"
"QToolButton:hover {\n"
"    background-color: rgba(0, 255, 255, 0.5);\n"
"    color: rgba(65, 65, 220, 0.5); /* 设置所有按钮字体为蓝色 */    \n"
"}\n"
"\n"
"/* ===== 按下效果 ===== */\n"
"QToolButton:pressed {\n"
"    background-color: rgb(0, 255, 255);\n"
"    color: rgb(255,255,255);\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/爱丽丝表情包/爱丽丝表情包/女仆/7.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Function3.setIcon(icon8)
        self.Function3.setIconSize(QtCore.QSize(100, 100))
        self.Function3.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.Function3.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.Function3.setAutoRaise(False)
        self.Function3.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.Function3.setObjectName("Function3")
        self.horizontalLayout.addWidget(self.Function3)
        self.Function4 = QtWidgets.QToolButton(parent=self.HomeButton)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.Function4.setFont(font)
        self.Function4.setStyleSheet("QToolButton {\n"
"    background-color: rgb(0, 255, 255);    /*设置背景颜色*/\n"
"    text-align : top;    /*文本放在顶层*/\n"
"    color: rgb(65, 65, 220); /* 设置所有按钮字体为蓝色 */\n"
"    padding-top: 10px;        /*调整内部距离*/\n"
"    padding-left: 10px;        /*调整内部距离*/\n"
"    padding-right: 10px;        /*调整内部距离*/\n"
"    border: 5px double rgb(65, 65, 220);  /*边框大小、双边框、边框颜色*/\n"
"}\n"
"\n"
"/* ===== 悬停效果 ===== */\n"
"QToolButton:hover {\n"
"    background-color: rgba(0, 255, 255, 0.5);\n"
"    color: rgba(65, 65, 220, 0.5); /* 设置所有按钮字体为蓝色 */    \n"
"}\n"
"\n"
"/* ===== 按下效果 ===== */\n"
"QToolButton:pressed {\n"
"    background-color: rgb(0, 255, 255);\n"
"    color: rgb(255,255,255);\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/爱丽丝表情包/爱丽丝表情包/非女仆/14.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Function4.setIcon(icon9)
        self.Function4.setIconSize(QtCore.QSize(100, 100))
        self.Function4.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.Function4.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.Function4.setAutoRaise(False)
        self.Function4.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.Function4.setObjectName("Function4")
        self.horizontalLayout.addWidget(self.Function4)
        self.verticalLayout_3.addWidget(self.HomeButton)
        self.verticalLayout_3.setStretch(0, 1)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/选项卡图标/选项卡图标/主页.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ModeWidget.addTab(self.Home, icon10, "")
        self.StateMonitor = QtWidgets.QWidget()
        self.StateMonitor.setObjectName("StateMonitor")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.StateMonitor)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.StateTabWidget = QtWidgets.QTabWidget(parent=self.StateMonitor)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setBold(True)
        self.StateTabWidget.setFont(font)
        self.StateTabWidget.setStyleSheet("/* 设置选项卡最小/最大尺寸 */\n"
"QTabBar::tab {\n"
"    border-right:  1px solid rgb(226, 230, 234);  /* 右边框显示颜色 */\n"
"    border-top-left-radius: 10px;    /* 左上角圆角半径 */\n"
"    border-bottom-right-radius: 0px; /* 右下角直角 */\n"
"    min-width: 70px;  /* 最小宽度 */\n"
"    min-height: 30px;  /* 最小高度 */\n"
"}\n"
"\n"
"/* 悬停状态 */\n"
"QTabBar::tab:hover {\n"
"    background:rgba(0, 0, 255,0.5);\n"
"    border-radius: 10px;        /*圆角*/\n"
"}\n"
"\n"
"/* 选中状态 */\n"
"QTabBar::tab:selected {\n"
"    border-top-right-radius: 10px;   /* 右上角圆角半径 */\n"
"    border-bottom-left-radius: 0px;  /* 左下角直角 */\n"
"    border-bottom-right-radius: 0px; /* 右下角直角 */\n"
"    background-color: rgba(0, 0, 255,0.3);\n"
"    color: black;             /* 选中文字色 */\n"
"    border-bottom: 10px solid rgb(0, 0, 255); /* 底部指示条 */\n"
"}")
        self.StateTabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.StateTabWidget.setDocumentMode(True)
        self.StateTabWidget.setTabsClosable(False)
        self.StateTabWidget.setMovable(True)
        self.StateTabWidget.setTabBarAutoHide(False)
        self.StateTabWidget.setObjectName("StateTabWidget")
        self.StateOutput = QtWidgets.QWidget()
        self.StateOutput.setObjectName("StateOutput")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.StateOutput)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.StateScrollAreaTip = QtWidgets.QLabel(parent=self.StateOutput)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        font.setBold(True)
        self.StateScrollAreaTip.setFont(font)
        self.StateScrollAreaTip.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.StateScrollAreaTip.setObjectName("StateScrollAreaTip")
        self.verticalLayout_10.addWidget(self.StateScrollAreaTip)
        self.StateScrollArea = QtWidgets.QScrollArea(parent=self.StateOutput)
        self.StateScrollArea.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        self.StateScrollArea.setStyleSheet("QScrollArea {\n"
"    border-radius:3px;\n"
"}\n"
"\n"
"#scrollArea{\n"
"border: 10px solid #c3c3c3;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"/*设置滚动条背景*/\n"
"QScrollBar:horizontal {\n"
"    border-radius:10px;\n"
"   height: 20px;\n"
"    background-color: rgba(0, 0, 0, 0.1);\n"
"    background: none;        /*没有背景,之前是网格*/\n"
"}\n"
"\n"
"/*设置滑动条*/\n"
"QScrollBar::handle:horizontal {\n"
"   border-radius:10px; \n"
"    background-color: rgb(0, 255, 255);\n"
" }\n"
"\n"
"QScrollBar::sub-line:horizontal,    /*滚动条顶部的按钮*/\n"
"QScrollBar::add-line:horizontal {        /*滚动条底部的按钮*/\n"
"    width: 0px; /*设置按钮大小为0(不显示)*/\n"
"}\n"
"")
        self.StateScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.StateScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.StateScrollArea.setWidgetResizable(True)
        self.StateScrollArea.setObjectName("StateScrollArea")
        self.StateWidget = QtWidgets.QWidget()
        self.StateWidget.setGeometry(QtCore.QRect(0, 0, 1186, 556))
        self.StateWidget.setObjectName("StateWidget")
        self.StateWidgetLayout = QtWidgets.QHBoxLayout(self.StateWidget)
        self.StateWidgetLayout.setObjectName("StateWidgetLayout")
        self.StateScrollArea.setWidget(self.StateWidget)
        self.verticalLayout_10.addWidget(self.StateScrollArea)
        self.StateTabWidget.addTab(self.StateOutput, "")
        self.Bind = QtWidgets.QWidget()
        self.Bind.setAutoFillBackground(False)
        self.Bind.setStyleSheet("QWidget {\n"
"    border-radius: 10px;        /*圆角*/\n"
"    border-color: rgb(0, 255, 255);\n"
"    border-width: 5px;        /*设置边框大小*/\n"
"}")
        self.Bind.setObjectName("Bind")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Bind)
        self.horizontalLayout_2.setContentsMargins(40, 20, 40, 20)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BindInputLayout = QtWidgets.QVBoxLayout()
        self.BindInputLayout.setContentsMargins(0, 29, 0, -1)
        self.BindInputLayout.setSpacing(10)
        self.BindInputLayout.setObjectName("BindInputLayout")
        self.QQGroupName = QtWidgets.QLineEdit(parent=self.Bind)
        self.QQGroupName.setMinimumSize(QtCore.QSize(309, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(False)
        self.QQGroupName.setFont(font)
        self.QQGroupName.setStyleSheet("QLineEdit {\n"
"border: 3px solid rgb(41, 57, 85); /*边框1px宽，颜色为深紫色*/\n"
"border-radius: 10px; /*边框圆角3px*/\n"
"background: white; /*背景色为白色*/\n"
"selection-background-color: green; /* 文本选中时的背景色*/\n"
"\n"
"}\n"
"/*悬停*/\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgba(0, 0, 0,0.4); /* 鼠标悬停时边框颜色为蓝色*/\n"
"}")
        self.QQGroupName.setInputMask("")
        self.QQGroupName.setText("")
        self.QQGroupName.setFrame(False)
        self.QQGroupName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.QQGroupName.setReadOnly(False)
        self.QQGroupName.setClearButtonEnabled(True)
        self.QQGroupName.setObjectName("QQGroupName")
        self.BindInputLayout.addWidget(self.QQGroupName)
        self.BotName = QtWidgets.QLineEdit(parent=self.Bind)
        self.BotName.setMinimumSize(QtCore.QSize(309, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(False)
        self.BotName.setFont(font)
        self.BotName.setStyleSheet("QLineEdit {\n"
"border: 3px solid rgb(41, 57, 85); /*边框1px宽，颜色为深紫色*/\n"
"border-radius: 10px; /*边框圆角3px*/\n"
"background: white; /*背景色为白色*/\n"
"selection-background-color: green; /* 文本选中时的背景色*/\n"
"\n"
"}\n"
"/*悬停*/\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgba(0, 0, 0,0.4); /* 鼠标悬停时边框颜色为蓝色*/\n"
"}")
        self.BotName.setInputMask("")
        self.BotName.setText("")
        self.BotName.setFrame(False)
        self.BotName.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.BotName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BotName.setReadOnly(False)
        self.BotName.setClearButtonEnabled(True)
        self.BotName.setObjectName("BotName")
        self.BindInputLayout.addWidget(self.BotName)
        self.Root = QtWidgets.QLineEdit(parent=self.Bind)
        self.Root.setMinimumSize(QtCore.QSize(309, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(False)
        self.Root.setFont(font)
        self.Root.setStyleSheet("QLineEdit {\n"
"border: 3px solid rgb(41, 57, 85); /*边框1px宽，颜色为深紫色*/\n"
"border-radius: 10px; /*边框圆角3px*/\n"
"background: white; /*背景色为白色*/\n"
"selection-background-color: green; /* 文本选中时的背景色*/\n"
"\n"
"}\n"
"/*悬停*/\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgba(0, 0, 0,0.4); /* 鼠标悬停时边框颜色为蓝色*/\n"
"}")
        self.Root.setInputMask("")
        self.Root.setText("")
        self.Root.setFrame(False)
        self.Root.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.Root.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Root.setReadOnly(False)
        self.Root.setClearButtonEnabled(True)
        self.Root.setObjectName("Root")
        self.BindInputLayout.addWidget(self.Root)
        self.ExitPassword = QtWidgets.QLineEdit(parent=self.Bind)
        self.ExitPassword.setMinimumSize(QtCore.QSize(309, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(False)
        self.ExitPassword.setFont(font)
        self.ExitPassword.setStyleSheet("QLineEdit {\n"
"border: 3px solid rgb(41, 57, 85); /*边框1px宽，颜色为深紫色*/\n"
"border-radius: 10px; /*边框圆角3px*/\n"
"background: white; /*背景色为白色*/\n"
"selection-background-color: green; /* 文本选中时的背景色*/\n"
"\n"
"}\n"
"/*悬停*/\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgba(0, 0, 0,0.4); /* 鼠标悬停时边框颜色为蓝色*/\n"
"}")
        self.ExitPassword.setInputMask("")
        self.ExitPassword.setText("")
        self.ExitPassword.setFrame(False)
        self.ExitPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.ExitPassword.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ExitPassword.setReadOnly(False)
        self.ExitPassword.setClearButtonEnabled(True)
        self.ExitPassword.setObjectName("ExitPassword")
        self.BindInputLayout.addWidget(self.ExitPassword)
        self.InitRole = QtWidgets.QLineEdit(parent=self.Bind)
        self.InitRole.setMinimumSize(QtCore.QSize(309, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(False)
        self.InitRole.setFont(font)
        self.InitRole.setStyleSheet("QLineEdit {\n"
"border: 3px solid rgb(41, 57, 85); /*边框1px宽，颜色为深紫色*/\n"
"border-radius: 10px; /*边框圆角3px*/\n"
"background: white; /*背景色为白色*/\n"
"selection-background-color: green; /* 文本选中时的背景色*/\n"
"\n"
"}\n"
"/*悬停*/\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgba(0, 0, 0,0.4); /* 鼠标悬停时边框颜色为蓝色*/\n"
"}")
        self.InitRole.setInputMask("")
        self.InitRole.setText("")
        self.InitRole.setFrame(False)
        self.InitRole.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.InitRole.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.InitRole.setReadOnly(False)
        self.InitRole.setClearButtonEnabled(True)
        self.InitRole.setObjectName("InitRole")
        self.BindInputLayout.addWidget(self.InitRole)
        self.QQGroupLocation = QtWidgets.QLineEdit(parent=self.Bind)
        self.QQGroupLocation.setMinimumSize(QtCore.QSize(309, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(False)
        self.QQGroupLocation.setFont(font)
        self.QQGroupLocation.setStyleSheet("QLineEdit {\n"
"border: 3px solid rgb(41, 57, 85); /*边框1px宽，颜色为深紫色*/\n"
"border-radius: 10px; /*边框圆角3px*/\n"
"background: white; /*背景色为白色*/\n"
"selection-background-color: green; /* 文本选中时的背景色*/\n"
"\n"
"}\n"
"/*悬停*/\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgba(0, 0, 0,0.4); /* 鼠标悬停时边框颜色为蓝色*/\n"
"}")
        self.QQGroupLocation.setInputMask("")
        self.QQGroupLocation.setText("")
        self.QQGroupLocation.setFrame(False)
        self.QQGroupLocation.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.QQGroupLocation.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.QQGroupLocation.setReadOnly(False)
        self.QQGroupLocation.setClearButtonEnabled(True)
        self.QQGroupLocation.setObjectName("QQGroupLocation")
        self.BindInputLayout.addWidget(self.QQGroupLocation)
        self.RemoveDangerousOrder = QtWidgets.QCheckBox(parent=self.Bind)
        self.RemoveDangerousOrder.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        self.RemoveDangerousOrder.setFont(font)
        self.RemoveDangerousOrder.setStyleSheet("/*整体控件 */\n"
"QCheckBox {\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"/*复选框本体*/\n"
"QCheckBox::indicator {\n"
"                width: 24px;\n"
"                height: 24px;\n"
"                border: 3px solid rgb(0,0,0);\n"
"                border-radius: 5px;\n"
"}\n"
"\n"
"/*未选中状态*/\n"
" QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"\n"
"/* 选中状态*/\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(85,255,255);\n"
"    border-color: rgb(0, 0, 255);\n"
"}\n"
"")
        self.RemoveDangerousOrder.setTristate(False)
        self.RemoveDangerousOrder.setObjectName("RemoveDangerousOrder")
        self.BindInputLayout.addWidget(self.RemoveDangerousOrder)
        self.AddOrRemoveLayout = QtWidgets.QHBoxLayout()
        self.AddOrRemoveLayout.setObjectName("AddOrRemoveLayout")
        self.AddOrChangeQQGroup = QtWidgets.QPushButton(parent=self.Bind)
        self.AddOrChangeQQGroup.setMinimumSize(QtCore.QSize(0, 40))
        self.AddOrChangeQQGroup.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(True)
        self.AddOrChangeQQGroup.setFont(font)
        self.AddOrChangeQQGroup.setStyleSheet("/**正常情况下样式**/\n"
"QPushButton{\n"
"    border-radius: 10px;        /*圆角*/\n"
"    border-width: 3px;        /*设置边框大小*/\n"
"    border-color: rgb(0,255,0);  /*边框颜色*/\n"
"    border-style: solid;        /*实线*/\n"
"    color: rgb(0, 255, 0);\n"
"    /*background-color: rgba(0, 255, 0,0.1);    */\n"
"    background-color: rgb(255,255,255)/*按钮背景颜色纯白*/\n"
"}\n"
"\n"
"/**鼠标停留在按钮上的样式**/\n"
"QPushButton::hover{    \n"
"    background-color: rgba(0, 255, 0,0.3);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/**鼠标按压下去的样式**/\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 255, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.AddOrChangeQQGroup.setAutoRepeat(False)
        self.AddOrChangeQQGroup.setAutoDefault(False)
        self.AddOrChangeQQGroup.setDefault(False)
        self.AddOrChangeQQGroup.setFlat(False)
        self.AddOrChangeQQGroup.setObjectName("AddOrChangeQQGroup")
        self.AddOrRemoveLayout.addWidget(self.AddOrChangeQQGroup)
        self.RemoveQQGroup = QtWidgets.QPushButton(parent=self.Bind)
        self.RemoveQQGroup.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(True)
        self.RemoveQQGroup.setFont(font)
        self.RemoveQQGroup.setStyleSheet("/**正常情况下样式**/\n"
"QPushButton{\n"
"    border-radius: 10px;        /*圆角*/\n"
"    border-width: 3px;        /*设置边框大小*/\n"
"    border-color: rgb(255, 0, 0);  /*边框颜色*/\n"
"    border-style: solid;        /*实线*/\n"
"    color: rgba(255, 0, 0,0.5);\n"
"    background-color: rgb(255, 255, 255);    /*按钮背景颜色纯白*/\n"
"}\n"
"\n"
"/**鼠标停留在按钮上的样式**/\n"
"QPushButton::hover{    \n"
"    background-color: rgba(255, 0, 0,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"/**鼠标按压下去的样式**/\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(255, 0, 0);  /*边框颜色*/\n"
"}\n"
"")
        self.RemoveQQGroup.setObjectName("RemoveQQGroup")
        self.AddOrRemoveLayout.addWidget(self.RemoveQQGroup)
        self.BindInputLayout.addLayout(self.AddOrRemoveLayout)
        spacerItem1 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.BindInputLayout.addItem(spacerItem1)
        self.SwitchReply = QtWidgets.QPushButton(parent=self.Bind)
        self.SwitchReply.setMinimumSize(QtCore.QSize(0, 40))
        self.SwitchReply.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(True)
        self.SwitchReply.setFont(font)
        self.SwitchReply.setStyleSheet("/**正常情况下样式**/\n"
"QPushButton{\n"
"    border-radius: 10px;        /*圆角*/\n"
"    border-width: 3px;        /*设置边框大小*/\n"
"    border-color: rgb(0, 85, 255);  /*边框颜色*/\n"
"    border-style: solid;        /*实线*/\n"
"    color: rgb(0, 85, 255);\n"
"    background-color: rgba(0, 85, 255,0.1);    /*按钮背景颜色纯白*/\n"
"}\n"
"\n"
"/**鼠标停留在按钮上的样式**/\n"
"QPushButton::hover{    \n"
"    background-color: rgba(0, 85, 255,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/**鼠标按压下去的样式**/\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.SwitchReply.setObjectName("SwitchReply")
        self.BindInputLayout.addWidget(self.SwitchReply)
        self.horizontalLayout_2.addLayout(self.BindInputLayout)
        self.QQGroupListState = QtWidgets.QGroupBox(parent=self.Bind)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        font.setBold(True)
        self.QQGroupListState.setFont(font)
        self.QQGroupListState.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.QQGroupListState.setFlat(False)
        self.QQGroupListState.setObjectName("QQGroupListState")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.QQGroupListState)
        self.verticalLayout_8.setContentsMargins(0, 30, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.QQGroupList = QtWidgets.QListWidget(parent=self.QQGroupListState)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        self.QQGroupList.setFont(font)
        self.QQGroupList.setStyleSheet("/* 设置整个列表控件的样式 */\n"
"QListWidget {\n"
"    outline: none;                    /* 移除选项前的焦点虚线框 */\n"
"    border: 3px solid rgb(0, 0, 0);  /* 边框大小、边框、边框颜色 */\n"
"    border-radius: 7px;               /* 圆角 */\n"
"    background-image: url(:/背景/背景/充能.jpg);\n"
"    background-size: cover; /* 保持比例，裁剪溢出部分 */\n"
"}\n"
"\n"
"/* 列表项默认样式*/\n"
"QListWidget::item {\n"
"    background-color: rgb(255,255,255); /* 普通行背景色 */\n"
"    border-bottom: 2px solid rgba(0,0,0,0.1); /* 底部边框 */\n"
"    color: rgb(0,0,0);                /* 文字颜色 */\n"
"    height: 40px;                     /* 项高度 */\n"
"    padding-left: 10px;               /* 左内边距 */\n"
"}\n"
"\n"
"/* 列表项悬停样式 */\n"
"QListWidget::item:hover {\n"
"    background-color: rgb(245, 245, 245);/* 选中背景色 */\n"
"    color: rgb(0,0,0);                   /* 悬停文字颜色 */\n"
"}\n"
"\n"
"/* 列表项选中样式 */\n"
"QListWidget::item:selected {\n"
"    background-color: rgb(228, 232, 237);        /* 悬停背景色 */\n"
"    color: rgb(0,0,0);                     /* 选中文字颜色 */\n"
"}\n"
"\n"
"/* 列表项选中且非焦点状态 */\n"
"QListWidget::item:selected:!active {\n"
"    background-color: rgb(228, 232, 237);        /* 悬停背景色 */\n"
"    color: rgb(0,0,0);                     /* 选中文字颜色 */\n"
"}\n"
"\n"
"/* 滚动条样式 */\n"
"QScrollBar:vertical {\n"
"    width: 10px;                      /* 垂直滚动条宽度 */\n"
"    background-color: rgba(0, 0, 0, 0.1);\n"
"}\n"
" /* 滚动条手柄*/\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(0, 0, 0, 0.2);              /* 滚动条手柄颜色 */\n"
"    min-height: 10px;                    /*最小宽度*/\n"
"    border-radius: 5px;    /*圆角大小*/\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"}")
        self.QQGroupList.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.QQGroupList.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.InternalMove)
        self.QQGroupList.setAlternatingRowColors(False)
        self.QQGroupList.setFlow(QtWidgets.QListView.Flow.TopToBottom)
        self.QQGroupList.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.QQGroupList.setObjectName("QQGroupList")
        self.verticalLayout_8.addWidget(self.QQGroupList)
        self.horizontalLayout_2.addWidget(self.QQGroupListState)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 15)
        self.StateTabWidget.addTab(self.Bind, "")
        self.verticalLayout_7.addWidget(self.StateTabWidget)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/选项卡图标/选项卡图标/状态监控.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ModeWidget.addTab(self.StateMonitor, icon11, "")
        self.KeyboardShortcut = QtWidgets.QWidget()
        self.KeyboardShortcut.setStyleSheet("QWidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.KeyboardShortcut.setObjectName("KeyboardShortcut")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.KeyboardShortcut)
        self.verticalLayout_5.setContentsMargins(70, 20, 70, 0)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.KeyboardShortcutLabel = QtWidgets.QLabel(parent=self.KeyboardShortcut)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(20)
        font.setBold(True)
        self.KeyboardShortcutLabel.setFont(font)
        self.KeyboardShortcutLabel.setStyleSheet("color: rgba(0, 0, 0,0.7);")
        self.KeyboardShortcutLabel.setObjectName("KeyboardShortcutLabel")
        self.verticalLayout_5.addWidget(self.KeyboardShortcutLabel)
        self.KeyboardShortcutTip = QtWidgets.QLabel(parent=self.KeyboardShortcut)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        font.setBold(True)
        self.KeyboardShortcutTip.setFont(font)
        self.KeyboardShortcutTip.setStyleSheet("color: rgb(131, 131, 131);")
        self.KeyboardShortcutTip.setObjectName("KeyboardShortcutTip")
        self.verticalLayout_5.addWidget(self.KeyboardShortcutTip)
        self.HotkeySelections = QtWidgets.QScrollArea(parent=self.KeyboardShortcut)
        self.HotkeySelections.setStyleSheet("QScrollArea {\n"
"    border: 5px solid rgb(240, 244, 249);  /*边框大小、边框样式、边框颜色*/\n"
"    border-top-left-radius: 20px;    /* 左上角圆角半径 */\n"
"    border-top-right-radius: 20px;   /* 右上角圆角半径 */\n"
"    background-color: rgb(240, 244, 249); /*背景色*/\n"
"}\n"
"/*设置垂直滚动条*/\n"
"QScrollBar:vertical {\n"
"    padding-top: 10px;        /*调整内部距离*/\n"
"    padding-bottom: 10px;    /*调整内部距离*/\n"
"    border-radius:10px; /*滚动条整体圆角*/\n"
"    width: 7px;    /*滚动条整体宽度*/\n"
"    background: none;        /*滚动条没有背景,之前是网格*/\n"
"}\n"
"\n"
"/*设置垂直滑动条手柄*/\n"
"QScrollBar::handle:vertical {\n"
"   border-radius:3px; \n"
"    background-color: rgb(0, 255, 255);    /*背景颜色*/\n"
"}\n"
"\n"
"/*手柄悬停颜色*/\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: rgba(0, 255, 255,0.3);        /*背景颜色*/\n"
"}\n"
"\n"
"/*垂直滚动条顶部和底部的按钮*/\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px; /*设置按钮大小为0(不显示)*/\n"
"}\n"
"\n"
"/*垂直滚动条未覆盖的区域*/\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical, {\n"
"    background-color: rgba(240, 244, 249,1); /*背景色*/\n"
"}\n"
"\n"
"\n"
"")
        self.HotkeySelections.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.HotkeySelections.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.HotkeySelections.setWidgetResizable(True)
        self.HotkeySelections.setObjectName("HotkeySelections")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1047, 677))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setStyleSheet("/*可视窗口背景*/\n"
"QWidget {\n"
"    background-color: rgb(240, 244, 249);\n"
"}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setSpacing(50)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.SwitchReply_5 = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.SwitchReply_5.setMinimumSize(QtCore.QSize(0, 40))
        self.SwitchReply_5.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(True)
        self.SwitchReply_5.setFont(font)
        self.SwitchReply_5.setStyleSheet("/**正常情况下样式**/\n"
"QPushButton{\n"
"    border-radius: 10px;        /*圆角*/\n"
"    border-width: 3px;        /*设置边框大小*/\n"
"    border-color: rgb(0, 85, 255);  /*边框颜色*/\n"
"    border-style: solid;        /*实线*/\n"
"    color: rgb(0, 85, 255);\n"
"    background-color: rgba(0, 85, 255,0.1);    /*按钮背景颜色纯白*/\n"
"    text-align : left;    /*文本放在左边*/\n"
"}\n"
"\n"
"/**鼠标停留在按钮上的样式**/\n"
"QPushButton::hover{    \n"
"    background-color: rgba(0, 85, 255,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/**鼠标按压下去的样式**/\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.SwitchReply_5.setObjectName("SwitchReply_5")
        self.verticalLayout_6.addWidget(self.SwitchReply_5)
        self.SwitchReply_3 = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.SwitchReply_3.setMinimumSize(QtCore.QSize(0, 40))
        self.SwitchReply_3.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(True)
        self.SwitchReply_3.setFont(font)
        self.SwitchReply_3.setStyleSheet("/**正常情况下样式**/\n"
"QPushButton{\n"
"    border-radius: 10px;        /*圆角*/\n"
"    border-width: 3px;        /*设置边框大小*/\n"
"    border-color: rgb(0, 85, 255);  /*边框颜色*/\n"
"    border-style: solid;        /*实线*/\n"
"    color: rgb(0, 85, 255);\n"
"    background-color: rgba(0, 85, 255,0.1);    /*按钮背景颜色纯白*/\n"
"    text-align : left;    /*文本放在左边*/\n"
"}\n"
"\n"
"/**鼠标停留在按钮上的样式**/\n"
"QPushButton::hover{    \n"
"    background-color: rgba(0, 85, 255,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/**鼠标按压下去的样式**/\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.SwitchReply_3.setObjectName("SwitchReply_3")
        self.verticalLayout_6.addWidget(self.SwitchReply_3)
        self.SwitchReply_4 = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.SwitchReply_4.setMinimumSize(QtCore.QSize(0, 40))
        self.SwitchReply_4.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(True)
        self.SwitchReply_4.setFont(font)
        self.SwitchReply_4.setStyleSheet("/**正常情况下样式**/\n"
"QPushButton{\n"
"    border-radius: 10px;        /*圆角*/\n"
"    border-width: 3px;        /*设置边框大小*/\n"
"    border-color: rgb(0, 85, 255);  /*边框颜色*/\n"
"    border-style: solid;        /*实线*/\n"
"    color: rgb(0, 85, 255);\n"
"    background-color: rgba(0, 85, 255,0.1);    /*按钮背景颜色纯白*/\n"
"    text-align : left;    /*文本放在左边*/\n"
"}\n"
"\n"
"/**鼠标停留在按钮上的样式**/\n"
"QPushButton::hover{    \n"
"    background-color: rgba(0, 85, 255,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/**鼠标按压下去的样式**/\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.SwitchReply_4.setObjectName("SwitchReply_4")
        self.verticalLayout_6.addWidget(self.SwitchReply_4)
        self.SwitchReply_6 = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.SwitchReply_6.setMinimumSize(QtCore.QSize(0, 40))
        self.SwitchReply_6.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(True)
        self.SwitchReply_6.setFont(font)
        self.SwitchReply_6.setStyleSheet("/**正常情况下样式**/\n"
"QPushButton{\n"
"    border-radius: 10px;        /*圆角*/\n"
"    border-width: 3px;        /*设置边框大小*/\n"
"    border-color: rgb(0, 85, 255);  /*边框颜色*/\n"
"    border-style: solid;        /*实线*/\n"
"    color: rgb(0, 85, 255);\n"
"    background-color: rgba(0, 85, 255,0.1);    /*按钮背景颜色纯白*/\n"
"    text-align : left;    /*文本放在左边*/\n"
"}\n"
"\n"
"/**鼠标停留在按钮上的样式**/\n"
"QPushButton::hover{    \n"
"    background-color: rgba(0, 85, 255,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/**鼠标按压下去的样式**/\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.SwitchReply_6.setObjectName("SwitchReply_6")
        self.verticalLayout_6.addWidget(self.SwitchReply_6)
        self.SwitchReply_2 = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.SwitchReply_2.setMinimumSize(QtCore.QSize(0, 40))
        self.SwitchReply_2.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(True)
        self.SwitchReply_2.setFont(font)
        self.SwitchReply_2.setStyleSheet("/**正常情况下样式**/\n"
"QPushButton{\n"
"    border-radius: 10px;        /*圆角*/\n"
"    border-width: 3px;        /*设置边框大小*/\n"
"    border-color: rgb(0, 85, 255);  /*边框颜色*/\n"
"    border-style: solid;        /*实线*/\n"
"    color: rgb(0, 85, 255);\n"
"    background-color: rgba(0, 85, 255,0.1);    /*按钮背景颜色纯白*/\n"
"    text-align : left;    /*文本放在左边*/\n"
"}\n"
"\n"
"/**鼠标停留在按钮上的样式**/\n"
"QPushButton::hover{    \n"
"    background-color: rgba(0, 85, 255,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/**鼠标按压下去的样式**/\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.SwitchReply_2.setObjectName("SwitchReply_2")
        self.verticalLayout_6.addWidget(self.SwitchReply_2)
        self.StateScrollAreaTip_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        font.setBold(True)
        self.StateScrollAreaTip_2.setFont(font)
        self.StateScrollAreaTip_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.StateScrollAreaTip_2.setObjectName("StateScrollAreaTip_2")
        self.verticalLayout_6.addWidget(self.StateScrollAreaTip_2)
        self.SwitchReply_7 = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.SwitchReply_7.setMinimumSize(QtCore.QSize(0, 40))
        self.SwitchReply_7.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(True)
        self.SwitchReply_7.setFont(font)
        self.SwitchReply_7.setStyleSheet("/**正常情况下样式**/\n"
"QPushButton{\n"
"    border-radius: 10px;        /*圆角*/\n"
"    border-width: 3px;        /*设置边框大小*/\n"
"    border-color: rgb(0, 85, 255);  /*边框颜色*/\n"
"    border-style: solid;        /*实线*/\n"
"    color: rgb(0, 85, 255);\n"
"    background-color: rgba(0, 85, 255,0.1);    /*按钮背景颜色纯白*/\n"
"    text-align : left;    /*文本放在左边*/\n"
"}\n"
"\n"
"/**鼠标停留在按钮上的样式**/\n"
"QPushButton::hover{    \n"
"    background-color: rgba(0, 85, 255,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/**鼠标按压下去的样式**/\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.SwitchReply_7.setObjectName("SwitchReply_7")
        self.verticalLayout_6.addWidget(self.SwitchReply_7)
        self.SwitchReply_8 = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.SwitchReply_8.setMinimumSize(QtCore.QSize(0, 40))
        self.SwitchReply_8.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(True)
        self.SwitchReply_8.setFont(font)
        self.SwitchReply_8.setStyleSheet("/**正常情况下样式**/\n"
"QPushButton{\n"
"    border-radius: 10px;        /*圆角*/\n"
"    border-width: 3px;        /*设置边框大小*/\n"
"    border-color: rgb(0, 85, 255);  /*边框颜色*/\n"
"    border-style: solid;        /*实线*/\n"
"    color: rgb(0, 85, 255);\n"
"    background-color: rgba(0, 85, 255,0.1);    /*按钮背景颜色纯白*/\n"
"    text-align : left;    /*文本放在左边*/\n"
"}\n"
"\n"
"/**鼠标停留在按钮上的样式**/\n"
"QPushButton::hover{    \n"
"    background-color: rgba(0, 85, 255,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/**鼠标按压下去的样式**/\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.SwitchReply_8.setObjectName("SwitchReply_8")
        self.verticalLayout_6.addWidget(self.SwitchReply_8)
        self.HotkeySelections.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.HotkeySelections)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/选项卡图标/选项卡图标/热键.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ModeWidget.addTab(self.KeyboardShortcut, icon12, "")
        self.QuestionLinks = QtWidgets.QWidget()
        self.QuestionLinks.setStyleSheet("QWidget {\n"
"    border-radius: 10px;        /*圆角*/\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.QuestionLinks.setObjectName("QuestionLinks")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.QuestionLinks)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.QuestionLinksScrollArea = QtWidgets.QScrollArea(parent=self.QuestionLinks)
        self.QuestionLinksScrollArea.setStyleSheet("QScrollArea {\n"
"    border: 5px solid rgb(255, 255, 255);  /*边框大小、边框样式、边框颜色*/\n"
"    border-radius:20px;         /*圆角*/    \n"
"}\n"
"/*设置垂直滚动条*/\n"
"QScrollBar:vertical {\n"
"    padding-top: 10px;        /*调整内部距离*/\n"
"    padding-bottom: 10px;    /*调整内部距离*/\n"
"    border-radius:10px; /*滚动条整体圆角*/\n"
"    width: 7px;    /*滚动条整体宽度*/\n"
"    background: none;        /*滚动条没有背景,之前是网格*/\n"
"    background-color: rgb(255, 255, 255);    /*背景颜色*/\n"
"}\n"
"\n"
"/*设置垂直滑动条手柄*/\n"
"QScrollBar::handle:vertical {\n"
"   border-radius:3px; \n"
"    background-color: rgb(0, 255, 255);    /*背景颜色*/\n"
"}\n"
"\n"
"/*手柄悬停颜色*/\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: rgba(0, 255, 255,0.3);        /*背景颜色*/\n"
"}\n"
"\n"
"/*垂直滚动条顶部和底部的按钮*/\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px; /*设置按钮大小为0(不显示)*/\n"
"}\n"
"\n"
"\n"
"")
        self.QuestionLinksScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.QuestionLinksScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.QuestionLinksScrollArea.setWidgetResizable(True)
        self.QuestionLinksScrollArea.setObjectName("QuestionLinksScrollArea")
        self.QuestionLinksScrollAreaWidget = QtWidgets.QWidget()
        self.QuestionLinksScrollAreaWidget.setGeometry(QtCore.QRect(0, 0, 1169, 1505))
        self.QuestionLinksScrollAreaWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.QuestionLinksScrollAreaWidget.setStyleSheet("/*可视窗口背景*/\n"
"QWidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.QuestionLinksScrollAreaWidget.setObjectName("QuestionLinksScrollAreaWidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.QuestionLinksScrollAreaWidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.QuestionLinksBackground = QtWidgets.QLabel(parent=self.QuestionLinksScrollAreaWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QuestionLinksBackground.sizePolicy().hasHeightForWidth())
        self.QuestionLinksBackground.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.QuestionLinksBackground.setFont(font)
        self.QuestionLinksBackground.setAcceptDrops(False)
        self.QuestionLinksBackground.setAutoFillBackground(False)
        self.QuestionLinksBackground.setStyleSheet("QLabel {\n"
"    border-radius: 10px;        /*圆角*/    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.QuestionLinksBackground.setText("### <span style=\"color:red\">禁止倒卖！禁止倒卖！禁止倒卖！！！</span>\n"
"\n"
"#### 📖 使用说明 📖  \n"
"1. **🆓 免费声明**  \n"
"   - 本软件为 **免费开源项目**！若你付了钱，请立刻退款！  \n"
"   - 🌟 GitHub 地址：[https://github.com/yandifei/ArisuQQChatAI](https://github.com/yandifei/ArisuQQChatAI)  \n"
"\n"
"2. **🚀 项目定位**  \n"
"   - 基于自研库 [DeepseekConversationEngine](https://github.com/yandifei/DeepseekConversationEngine) 📦 开发的 **示例程序**，用于演示功能与开发流程。  \n"
"   - 🔍 指令系统详解请参考库文档 → [专属指令快捷调参](https://github.com/yandifei/DeepseekConversationEngine)  \n"
"\n"
"3. **🔑 密钥配置必读**  \n"
"   - 使用前 **必须配置** DeepSeek-API 密钥 🔐！  \n"
"   - 获取方式：  \n"
"     - 📄 查看目录文档《爱丽丝QQ聊天AI.pdf》  \n"
"     - 📺 观看教程视频  \n"
"     - 🤖 咨询 AI  \n"
"     - 🌐 [DeepSeek API Key 官网](https://platform.deepseek.com/api_keys)  \n"
"\n"
"4. **🎨 QQ 主题设置**  \n"
"   - 需在 QQ 设置中将 **主题风格调整为「极简白」**，否则可能报错！ ⚠️  \n"
"\n"
"5. **✨ 支持项目**  \n"
"   - 喜欢本项目？感谢你的使用！开源不易，欢迎在 GitHub 点亮 **Star** 🌟 → [项目地址](https://github.com/yandifei/ArisuQQChatAI)  \n"
"\n"
"#### ⚠️ 免责声明 ⚠️  \n"
"1. **⚠️ 内容免责**  \n"
"   - 本软件通过 DeepSeek API 生成的内容 **不代表开发者观点**，其准确性、适当性由使用者 **自行判断并承担全部责任**。  \n"
"   - 🤖 AI 可能产生错误、偏见或不适宜内容，开发者 **不对此引发的任何后果负责**。  \n"
"\n"
"2. **⚡ 封号风险警示**  \n"
"   - 若因使用本软件导致 QQ 号被封(如：Q群中发送禁漫天堂的本子被举报等)，开发者 **概不负责**！  \n"
"   - 🎭（非要作死？开发者也拦不住！已提供移除危险指令选项，请自行承担风险！）  \n"
"\n"
"3. **🚫 使用限制**  \n"
"   - 📜 基于 MIT 协议开源，保留原始版权，可自由修改。  \n"
"   - ❌ **严禁** 用于引流、色情、键政、消息轰炸等非法用途！  \n"
"\n"
"4. **💖 核心目标**  \n"
"   - 打造 DeepSeek API 接口，实现 **爱丽丝** + **满分问题解答** 🧠 + 提供 **情绪价值** 💖！  \n"
"\n"
"5. **🔐 隐私与安全**  \n"
"   - 项目开源透明，**绝不非法获取用户隐私**。  \n"
"   - ⚠️ 若私自重新打包分发导致聊天记录泄露，**开发者概不负责**，请从[Github官网下载](https://github.com/yandifei/ArisuQQChatAI)！  \n"
"\n"
"6. **🔧 密钥安全说明**  \n"
"   - 已妥善设计 API 密钥存储机制 🔒。  \n"
"   - 如因个人操作导致密钥泄露，请 **立即删除并更换** 🔑！  \n"
"   - 本项目 **不承担** 用户操作失误引发的密钥泄露责任。 \n"
"\n"
"#### 问题反馈\n"
"- 其实还有别的项目要研发和个人学习，没时间处理。\n"
"- 提交 [Issues](https://github.com/yandifei/ArisuQQChatAI/issues) 或 邮箱3058439878@qq.com")
        self.QuestionLinksBackground.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.QuestionLinksBackground.setScaledContents(False)
        self.QuestionLinksBackground.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.QuestionLinksBackground.setWordWrap(True)
        self.QuestionLinksBackground.setOpenExternalLinks(True)
        self.QuestionLinksBackground.setObjectName("QuestionLinksBackground")
        self.verticalLayout_11.addWidget(self.QuestionLinksBackground)
        self.QuestionLinksScrollArea.setWidget(self.QuestionLinksScrollAreaWidget)
        self.verticalLayout_2.addWidget(self.QuestionLinksScrollArea)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/选项卡图标/选项卡图标/问题链接.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ModeWidget.addTab(self.QuestionLinks, icon13, "")
        self.Settings = QtWidgets.QWidget()
        self.Settings.setAutoFillBackground(False)
        self.Settings.setStyleSheet("QWidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.Settings.setObjectName("Settings")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.Settings)
        self.verticalLayout_9.setContentsMargins(70, 30, 70, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.SettingsScrollArea = QtWidgets.QScrollArea(parent=self.Settings)
        self.SettingsScrollArea.setMinimumSize(QtCore.QSize(0, 500))
        self.SettingsScrollArea.setStyleSheet("QScrollArea {\n"
"    border: 5px solid rgb(240, 244, 249);  /*边框大小、边框样式、边框颜色*/\n"
"    border-top-left-radius: 20px;    /* 左上角圆角半径 */\n"
"    border-top-right-radius: 20px;   /* 右上角圆角半径 */\n"
"    background-color: rgb(240, 244, 249); /*背景色*/\n"
"}\n"
"/*设置垂直滚动条*/\n"
"QScrollBar:vertical {\n"
"    padding-top: 10px;        /*调整内部距离*/\n"
"    padding-bottom: 10px;    /*调整内部距离*/\n"
"    border-radius:10px; /*滚动条整体圆角*/\n"
"    width: 7px;    /*滚动条整体宽度*/\n"
"    background: none;        /*滚动条没有背景,之前是网格*/\n"
"}\n"
"\n"
"/*设置垂直滑动条手柄*/\n"
"QScrollBar::handle:vertical {\n"
"   border-radius:3px; \n"
"    background-color: rgb(0, 255, 255);    /*背景颜色*/\n"
"}\n"
"\n"
"/*手柄悬停颜色*/\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: rgba(0, 255, 255,0.3);        /*背景颜色*/\n"
"}\n"
"\n"
"/*垂直滚动条顶部和底部的按钮*/\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px; /*设置按钮大小为0(不显示)*/\n"
"}\n"
"\n"
"/*垂直滚动条未覆盖的区域*/\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical, {\n"
"    background-color: rgba(240, 244, 249,1); /*背景色*/\n"
"}\n"
"\n"
"\n"
"")
        self.SettingsScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.SettingsScrollArea.setWidgetResizable(True)
        self.SettingsScrollArea.setObjectName("SettingsScrollArea")
        self.SettingsScrollAreaWidget = QtWidgets.QWidget()
        self.SettingsScrollAreaWidget.setGeometry(QtCore.QRect(0, 0, 1054, 478))
        self.SettingsScrollAreaWidget.setStyleSheet("/*可视窗口背景*/\n"
"QWidget {\n"
"    background-color: rgb(240, 244, 249);\n"
"}")
        self.SettingsScrollAreaWidget.setObjectName("SettingsScrollAreaWidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.SettingsScrollAreaWidget)
        self.verticalLayout_12.setContentsMargins(50, 20, 50, 10)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_4.setSpacing(37)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.APIKeyState = QtWidgets.QGroupBox(parent=self.SettingsScrollAreaWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.APIKeyState.setFont(font)
        self.APIKeyState.setStyleSheet("QGroupBox {\n"
"    border: none;            /*无边框*/\n"
"    color: rgb(0, 255, 0);\n"
"}")
        self.APIKeyState.setTitle("")
        self.APIKeyState.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.APIKeyState.setFlat(False)
        self.APIKeyState.setCheckable(False)
        self.APIKeyState.setObjectName("APIKeyState")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.APIKeyState)
        self.horizontalLayout_3.setContentsMargins(0, 24, 15, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.APIKeyInput = QtWidgets.QLineEdit(parent=self.APIKeyState)
        self.APIKeyInput.setMinimumSize(QtCore.QSize(309, 40))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(17)
        font.setBold(True)
        self.APIKeyInput.setFont(font)
        self.APIKeyInput.setStyleSheet("QLineEdit {\n"
"    border: 3px solid rgb(41, 57, 85); /*边框1px宽，颜色为深紫色*/\n"
"    border-radius: 10px; /*边框圆角3px*/\n"
"    background: white; /*背景色为白色*/\n"
"    selection-background-color: green; /* 文本选中时的背景色*/\n"
"}\n"
"/*悬停*/\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgba(0, 0, 0,0.4); /* 鼠标悬停时边框颜色为蓝色*/\n"
"}\n"
"\n"
"/*密码模式的颜色*/\n"
"QLineEdit[echoMode=\"2\"] {\n"
"    color: rgb(0,0, 0);\n"
"}")
        self.APIKeyInput.setInputMask("")
        self.APIKeyInput.setText("")
        self.APIKeyInput.setFrame(False)
        self.APIKeyInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.APIKeyInput.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.APIKeyInput.setReadOnly(False)
        self.APIKeyInput.setClearButtonEnabled(True)
        self.APIKeyInput.setObjectName("APIKeyInput")
        self.horizontalLayout_3.addWidget(self.APIKeyInput)
        self.APIKeyConfirm = QtWidgets.QPushButton(parent=self.APIKeyState)
        self.APIKeyConfirm.setMinimumSize(QtCore.QSize(70, 40))
        self.APIKeyConfirm.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(True)
        self.APIKeyConfirm.setFont(font)
        self.APIKeyConfirm.setStyleSheet("/**正常情况下样式**/\n"
"QPushButton{\n"
"    border-radius: 10px;        /*圆角*/\n"
"    border-width: 3px;        /*设置边框大小*/\n"
"    border-color: rgb(77, 107, 254);  /*边框颜色*/\n"
"    border-style: solid;        /*实线*/\n"
"    color: rgb(77, 107, 254);\n"
"    background-color: rgba(77, 107, 254,0.2);    /*按钮背景颜色纯白*/\n"
"}\n"
"\n"
"/**鼠标停留在按钮上的样式**/\n"
"QPushButton::hover{    \n"
"    background-color: rgba(77, 107, 254,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/**鼠标按压下去的样式**/\n"
"QPushButton:pressed {\n"
"    background-color: rgb(77, 107, 254);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.APIKeyConfirm.setAutoRepeat(False)
        self.APIKeyConfirm.setAutoDefault(False)
        self.APIKeyConfirm.setDefault(False)
        self.APIKeyConfirm.setFlat(False)
        self.APIKeyConfirm.setObjectName("APIKeyConfirm")
        self.horizontalLayout_3.addWidget(self.APIKeyConfirm)
        self.horizontalLayout_4.addWidget(self.APIKeyState)
        self.LogicCPUCountState = QtWidgets.QGroupBox(parent=self.SettingsScrollAreaWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LogicCPUCountState.setFont(font)
        self.LogicCPUCountState.setStyleSheet("QGroupBox {\n"
"    border: none;            /*无边框*/\n"
"    color: rgb(0, 255, 0);\n"
"}")
        self.LogicCPUCountState.setTitle("")
        self.LogicCPUCountState.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.LogicCPUCountState.setFlat(False)
        self.LogicCPUCountState.setCheckable(False)
        self.LogicCPUCountState.setObjectName("LogicCPUCountState")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.LogicCPUCountState)
        self.horizontalLayout_5.setContentsMargins(0, 24, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.LogicCPUCount = QtWidgets.QLineEdit(parent=self.LogicCPUCountState)
        self.LogicCPUCount.setMinimumSize(QtCore.QSize(309, 40))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(17)
        font.setBold(True)
        self.LogicCPUCount.setFont(font)
        self.LogicCPUCount.setStyleSheet("QLineEdit {\n"
"    border: 3px solid rgb(41, 57, 85); /*边框1px宽，颜色为深紫色*/\n"
"    border-radius: 10px; /*边框圆角3px*/\n"
"    background: white; /*背景色为白色*/\n"
"    selection-background-color: green; /* 文本选中时的背景色*/\n"
"}\n"
"/*悬停*/\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgba(0, 0, 0,0.4); /* 鼠标悬停时边框颜色为蓝色*/\n"
"}\n"
"\n"
"/*正常模式的颜色*/\n"
"QLineEdit[echoMode=\"0\"] {\n"
"    color: rgb(0,0, 0);\n"
"}")
        self.LogicCPUCount.setInputMask("")
        self.LogicCPUCount.setText("")
        self.LogicCPUCount.setFrame(False)
        self.LogicCPUCount.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LogicCPUCount.setReadOnly(False)
        self.LogicCPUCount.setClearButtonEnabled(True)
        self.LogicCPUCount.setObjectName("LogicCPUCount")
        self.horizontalLayout_5.addWidget(self.LogicCPUCount)
        self.LogicCPUCountConfirm = QtWidgets.QPushButton(parent=self.LogicCPUCountState)
        self.LogicCPUCountConfirm.setMinimumSize(QtCore.QSize(70, 40))
        self.LogicCPUCountConfirm.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(True)
        self.LogicCPUCountConfirm.setFont(font)
        self.LogicCPUCountConfirm.setStyleSheet("/**正常情况下样式**/\n"
"QPushButton{\n"
"    border-radius: 10px;        /*圆角*/\n"
"    border-width: 3px;        /*设置边框大小*/\n"
"    border-color: rgb(77, 107, 254);  /*边框颜色*/\n"
"    border-style: solid;        /*实线*/\n"
"    color: rgb(77, 107, 254);\n"
"    background-color: rgba(77, 107, 254,0.2);    /*按钮背景颜色纯白*/\n"
"}\n"
"\n"
"/**鼠标停留在按钮上的样式**/\n"
"QPushButton::hover{    \n"
"    background-color: rgba(77, 107, 254,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/**鼠标按压下去的样式**/\n"
"QPushButton:pressed {\n"
"    background-color: rgb(77, 107, 254);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.LogicCPUCountConfirm.setAutoRepeat(False)
        self.LogicCPUCountConfirm.setAutoDefault(False)
        self.LogicCPUCountConfirm.setDefault(False)
        self.LogicCPUCountConfirm.setFlat(False)
        self.LogicCPUCountConfirm.setObjectName("LogicCPUCountConfirm")
        self.horizontalLayout_5.addWidget(self.LogicCPUCountConfirm)
        self.horizontalLayout_4.addWidget(self.LogicCPUCountState)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(0, 0, 40, -1)
        self.gridLayout_2.setHorizontalSpacing(51)
        self.gridLayout_2.setVerticalSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 2, 0, 1, 1)
        self.WinResetTimeState = QtWidgets.QGroupBox(parent=self.SettingsScrollAreaWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.WinResetTimeState.setFont(font)
        self.WinResetTimeState.setStyleSheet("QGroupBox {\n"
"    border: none;            /*无边框*/\n"
"    color: green;\n"
"}")
        self.WinResetTimeState.setTitle("")
        self.WinResetTimeState.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.WinResetTimeState.setFlat(False)
        self.WinResetTimeState.setCheckable(False)
        self.WinResetTimeState.setObjectName("WinResetTimeState")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.WinResetTimeState)
        self.horizontalLayout_7.setContentsMargins(0, 20, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.WinResetTime = QtWidgets.QLineEdit(parent=self.WinResetTimeState)
        self.WinResetTime.setMinimumSize(QtCore.QSize(309, 40))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(17)
        font.setBold(True)
        self.WinResetTime.setFont(font)
        self.WinResetTime.setStyleSheet("QLineEdit {\n"
"    border: 3px solid rgb(41, 57, 85); /*边框1px宽，颜色为深紫色*/\n"
"    border-radius: 10px; /*边框圆角3px*/\n"
"    background: white; /*背景色为白色*/\n"
"    selection-background-color: green; /* 文本选中时的背景色*/\n"
"}\n"
"/*悬停*/\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgba(0, 0, 0,0.4); /* 鼠标悬停时边框颜色为蓝色*/\n"
"}\n"
"\n"
"/*正常模式的颜色*/\n"
"QLineEdit[echoMode=\"0\"] {\n"
"    color: rgb(0,0, 0);\n"
"}")
        self.WinResetTime.setInputMask("")
        self.WinResetTime.setFrame(False)
        self.WinResetTime.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.WinResetTime.setReadOnly(False)
        self.WinResetTime.setClearButtonEnabled(True)
        self.WinResetTime.setObjectName("WinResetTime")
        self.horizontalLayout_7.addWidget(self.WinResetTime)
        self.gridLayout_2.addWidget(self.WinResetTimeState, 1, 0, 1, 1)
        self.ThreadRestartTimeState = QtWidgets.QGroupBox(parent=self.SettingsScrollAreaWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ThreadRestartTimeState.setFont(font)
        self.ThreadRestartTimeState.setStyleSheet("QGroupBox {\n"
"    border: none;            /*无边框*/\n"
"    color: green;\n"
"}")
        self.ThreadRestartTimeState.setTitle("")
        self.ThreadRestartTimeState.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.ThreadRestartTimeState.setFlat(False)
        self.ThreadRestartTimeState.setCheckable(False)
        self.ThreadRestartTimeState.setObjectName("ThreadRestartTimeState")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.ThreadRestartTimeState)
        self.horizontalLayout_6.setContentsMargins(0, 20, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ThreadRestartTime = QtWidgets.QLineEdit(parent=self.ThreadRestartTimeState)
        self.ThreadRestartTime.setMinimumSize(QtCore.QSize(309, 40))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(17)
        font.setBold(True)
        self.ThreadRestartTime.setFont(font)
        self.ThreadRestartTime.setStyleSheet("QLineEdit {\n"
"    border: 3px solid rgb(41, 57, 85); /*边框1px宽，颜色为深紫色*/\n"
"    border-radius: 10px; /*边框圆角3px*/\n"
"    background: white; /*背景色为白色*/\n"
"    selection-background-color: green; /* 文本选中时的背景色*/\n"
"}\n"
"/*悬停*/\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgba(0, 0, 0,0.4); /* 鼠标悬停时边框颜色为蓝色*/\n"
"}\n"
"\n"
"/*正常模式的颜色*/\n"
"QLineEdit[echoMode=\"0\"] {\n"
"    color: rgb(0,0, 0);\n"
"}")
        self.ThreadRestartTime.setInputMask("")
        self.ThreadRestartTime.setFrame(False)
        self.ThreadRestartTime.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ThreadRestartTime.setReadOnly(False)
        self.ThreadRestartTime.setClearButtonEnabled(True)
        self.ThreadRestartTime.setObjectName("ThreadRestartTime")
        self.horizontalLayout_6.addWidget(self.ThreadRestartTime)
        self.gridLayout_2.addWidget(self.ThreadRestartTimeState, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(parent=self.SettingsScrollAreaWidget)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    border: none;            /*无边框*/\n"
"    color: rgb(0, 255, 0);\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(9, 21, -1, -1)
        self.gridLayout.setHorizontalSpacing(50)
        self.gridLayout.setVerticalSpacing(53)
        self.gridLayout.setObjectName("gridLayout")
        self.OpenRoleDir = QtWidgets.QPushButton(parent=self.groupBox)
        self.OpenRoleDir.setMinimumSize(QtCore.QSize(0, 40))
        self.OpenRoleDir.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(True)
        self.OpenRoleDir.setFont(font)
        self.OpenRoleDir.setStyleSheet("/**正常情况下样式**/\n"
"QPushButton{\n"
"    border-radius: 10px;        /*圆角*/\n"
"    border: 3px solid rgb(85, 85, 255);  /*边框大小、边框样式、边框颜色*/\n"
"    color: rgb(85, 85, 255);\n"
"    /*background-color: rgba(0, 255, 0,0.1);    */\n"
"    background-color: rgba(85, 85, 255,0.1);/*按钮背景颜色纯白*/\n"
"}\n"
"\n"
"/**鼠标停留在按钮上的样式**/\n"
"QPushButton::hover{    \n"
"    background-color: rgba(85, 85, 255,0.3);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/**鼠标按压下去的样式**/\n"
"QPushButton:pressed {\n"
"    background-color: rgb(85, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.OpenRoleDir.setAutoRepeat(False)
        self.OpenRoleDir.setAutoDefault(False)
        self.OpenRoleDir.setDefault(False)
        self.OpenRoleDir.setFlat(False)
        self.OpenRoleDir.setObjectName("OpenRoleDir")
        self.gridLayout.addWidget(self.OpenRoleDir, 1, 0, 1, 2)
        self.LogQueryDir = QtWidgets.QPushButton(parent=self.groupBox)
        self.LogQueryDir.setMinimumSize(QtCore.QSize(0, 40))
        self.LogQueryDir.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(True)
        self.LogQueryDir.setFont(font)
        self.LogQueryDir.setStyleSheet("/**正常情况下样式**/\n"
"QPushButton{\n"
"    border-radius: 10px;        /*圆角*/\n"
"    border-width: 3px;        /*设置边框大小*/\n"
"    border-color: rgb(85, 85, 255);  /*边框颜色*/\n"
"    border-style: solid;        /*实线*/\n"
"    color: rgb(85, 85, 255);\n"
"    /*background-color: rgba(0, 255, 0,0.1);    */\n"
"    background-color: rgba(85, 85, 255,0.1)/*按钮背景颜色纯白*/\n"
"}\n"
"\n"
"/**鼠标停留在按钮上的样式**/\n"
"QPushButton::hover{    \n"
"    background-color: rgba(85, 85, 255,0.3);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/**鼠标按压下去的样式**/\n"
"QPushButton:pressed {\n"
"    background-color: rgb(85, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"`")
        self.LogQueryDir.setAutoRepeat(False)
        self.LogQueryDir.setAutoDefault(False)
        self.LogQueryDir.setDefault(False)
        self.LogQueryDir.setFlat(False)
        self.LogQueryDir.setObjectName("LogQueryDir")
        self.gridLayout.addWidget(self.LogQueryDir, 2, 0, 1, 2)
        self.RestoreNavigationBarSortingButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.RestoreNavigationBarSortingButton.setMinimumSize(QtCore.QSize(0, 40))
        self.RestoreNavigationBarSortingButton.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(True)
        self.RestoreNavigationBarSortingButton.setFont(font)
        self.RestoreNavigationBarSortingButton.setStyleSheet("/**正常情况下样式**/\n"
"QPushButton{\n"
"    border-radius: 10px;        /*圆角*/\n"
"    border-width: 3px;        /*设置边框大小*/\n"
"    border-color: rgb(85, 85, 255);  /*边框颜色*/\n"
"    border-style: solid;        /*实线*/\n"
"    color: rgb(85, 85, 255);\n"
"    /*background-color: rgba(0, 255, 0,0.1);    */\n"
"    background-color: rgba(85, 85, 255,0.1)/*按钮背景颜色纯白*/\n"
"}\n"
"\n"
"/**鼠标停留在按钮上的样式**/\n"
"QPushButton::hover{    \n"
"    background-color: rgba(85, 85, 255,0.3);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/**鼠标按压下去的样式**/\n"
"QPushButton:pressed {\n"
"    background-color: rgb(85, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.RestoreNavigationBarSortingButton.setObjectName("RestoreNavigationBarSortingButton")
        self.gridLayout.addWidget(self.RestoreNavigationBarSortingButton, 0, 2, 1, 1)
        self.JMDownloadStrategy = QtWidgets.QPushButton(parent=self.groupBox)
        self.JMDownloadStrategy.setMinimumSize(QtCore.QSize(0, 40))
        self.JMDownloadStrategy.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(True)
        self.JMDownloadStrategy.setFont(font)
        self.JMDownloadStrategy.setStyleSheet("/**正常情况下样式**/\n"
"QPushButton{\n"
"    border-radius: 10px;        /*圆角*/\n"
"    border-width: 3px;        /*设置边框大小*/\n"
"    border-color: rgb(85, 85, 255);  /*边框颜色*/\n"
"    border-style: solid;        /*实线*/\n"
"    color: rgb(85, 85, 255);\n"
"    /*background-color: rgba(0, 255, 0,0.1);    */\n"
"    background-color: rgba(85, 85, 255,0.1)/*按钮背景颜色纯白*/\n"
"}\n"
"\n"
"/**鼠标停留在按钮上的样式**/\n"
"QPushButton::hover{    \n"
"    background-color: rgba(85, 85, 255,0.3);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/**鼠标按压下去的样式**/\n"
"QPushButton:pressed {\n"
"    background-color: rgb(85, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.JMDownloadStrategy.setAutoRepeat(False)
        self.JMDownloadStrategy.setAutoDefault(False)
        self.JMDownloadStrategy.setDefault(False)
        self.JMDownloadStrategy.setFlat(False)
        self.JMDownloadStrategy.setObjectName("JMDownloadStrategy")
        self.gridLayout.addWidget(self.JMDownloadStrategy, 2, 2, 1, 1)
        self.InitialInterfaceLocationComboBox = QtWidgets.QComboBox(parent=self.groupBox)
        self.InitialInterfaceLocationComboBox.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.InitialInterfaceLocationComboBox.setFont(font)
        self.InitialInterfaceLocationComboBox.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.InitialInterfaceLocationComboBox.setStyleSheet("/*本体样式(不包括下拉窗口)*/\n"
"QComboBox{\n"
"    \n"
"    color: rgb(85, 85, 255);    /*字体颜色*/\n"
"      border-radius:10px 10px 10px 10px;\n"
"    background-color: rgba(85, 85, 255,0.1);/*背景颜色*/\n"
"    border: 3px solid rgb(85, 85, 255);  /*边框大小、边框样式、边框颜色*/\n"
"}\n"
"/*本体样式下拉状态(不包括下拉窗口)*/\n"
"QComboBox:on {\n"
"    border-top-left-radius: 10px;    /* 左上角圆角半径 */\n"
"    border-top-right-radius: 10px;   /* 右上角圆角半径 */\n"
"    border-bottom-left-radius: 0px;  /* 左下角直角 */\n"
"    border-bottom-right-radius: 0px; /* 右下角直角 */\n"
"}\n"
"\n"
"/*下拉的按钮*/\n"
"QComboBox::drop-down {\n"
"  subcontrol-position: right;\n"
"    border:none; /*无边框*/\n"
"    padding-right: 10px;        /*调整内部距离(配合下拉图标一起才有效)*/\n"
"}\n"
"\n"
"/*右侧下拉箭头图标 */\n"
"QComboBox::down-arrow {\n"
"    image: url(:/控件图标/控件图标/chevron-down.png);\n"
"    width: 20px;    /*限制图标大小*/\n"
"    height:20px;/*限制图标大小*/\n"
"    padding-right: 10px;        /*调整内部距离(配合下拉按钮一起才有效)*/\n"
"}\n"
"\n"
"/*右侧下拉箭头图标(下拉状态)*/\n"
"QComboBox::down-arrow:on {\n"
"    image: url(:/控件图标/控件图标/chevron-up.png);\n"
"}\n"
"/*下拉的列表*/\n"
"QComboBox QAbstractItemView{\n"
"    background-color: rgb(225, 228, 250);/*背景颜色(蓝底经过计算的不透明)*/\n"
"/*    border:none;*/\n"
"    border: 3px solid rgb(85, 85, 255);    /*边框*/\n"
"    border-top-left-radius: 0px;    /* 左上角圆角半径 */\n"
"    border-top-right-radius: 0px;   /* 右上角圆角半径 */\n"
"    border-bottom-left-radius: 10px;  /* 左下角直角 */\n"
"    border-bottom-right-radius: 10px; /* 右下角直角 */\n"
"    border-top: none;    /* 无上边框 */\n"
"     outline: 0px; /*下拉项去虚线*/\n"
"}\n"
"/*=====================下拉框的选项===================*/\n"
"/*下拉框的选项*/\n"
"QComboBox QAbstractItemView::item{\n"
"    text-align: center; /*文本居中显示*/\n"
"    color: rgb(85, 85, 255);    /*字体颜色*/\n"
"}\n"
"/*下拉框的选项被选中*/\n"
"QComboBox QAbstractItemView::item:selected{\n"
"    background-color: rgba(85, 85, 255,0.3);\n"
"}\n"
"")
        self.InitialInterfaceLocationComboBox.setIconSize(QtCore.QSize(40, 40))
        self.InitialInterfaceLocationComboBox.setObjectName("InitialInterfaceLocationComboBox")
        self.InitialInterfaceLocationComboBox.addItem(icon7, "")
        self.InitialInterfaceLocationComboBox.addItem(icon6, "")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/爱丽丝表情包/爱丽丝表情包/非女仆/4.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.InitialInterfaceLocationComboBox.addItem(icon14, "")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/爱丽丝表情包/爱丽丝表情包/女仆/6.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.InitialInterfaceLocationComboBox.addItem(icon15, "")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/爱丽丝表情包/爱丽丝表情包/非女仆/15.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.InitialInterfaceLocationComboBox.addItem(icon16, "")
        self.gridLayout.addWidget(self.InitialInterfaceLocationComboBox, 0, 0, 1, 2)
        self.KeywordReplyDir = QtWidgets.QPushButton(parent=self.groupBox)
        self.KeywordReplyDir.setMinimumSize(QtCore.QSize(0, 40))
        self.KeywordReplyDir.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(True)
        self.KeywordReplyDir.setFont(font)
        self.KeywordReplyDir.setStyleSheet("/**正常情况下样式**/\n"
"QPushButton{\n"
"    border-radius: 10px;        /*圆角*/\n"
"    border-width: 3px;        /*设置边框大小*/\n"
"    border-color: rgb(85, 85, 255);  /*边框颜色*/\n"
"    border-style: solid;        /*实线*/\n"
"    color: rgb(85, 85, 255);\n"
"    /*background-color: rgba(0, 255, 0,0.1);    */\n"
"    background-color: rgba(85, 85, 255,0.1)/*按钮背景颜色纯白*/\n"
"}\n"
"\n"
"/**鼠标停留在按钮上的样式**/\n"
"QPushButton::hover{    \n"
"    background-color: rgba(85, 85, 255,0.3);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/**鼠标按压下去的样式**/\n"
"QPushButton:pressed {\n"
"    background-color: rgb(85, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.KeywordReplyDir.setAutoRepeat(False)
        self.KeywordReplyDir.setAutoDefault(False)
        self.KeywordReplyDir.setDefault(False)
        self.KeywordReplyDir.setFlat(False)
        self.KeywordReplyDir.setObjectName("KeywordReplyDir")
        self.gridLayout.addWidget(self.KeywordReplyDir, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 1, 3, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.Uninstall = QtWidgets.QPushButton(parent=self.SettingsScrollAreaWidget)
        self.Uninstall.setMinimumSize(QtCore.QSize(130, 40))
        self.Uninstall.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        font.setBold(True)
        self.Uninstall.setFont(font)
        self.Uninstall.setStyleSheet("/**正常情况下样式**/\n"
"QPushButton{\n"
"    border-radius: 10px;        /*圆角*/\n"
"    border-width: 3px;        /*设置边框大小*/\n"
"    border-color: rgb(255, 0, 0);  /*边框颜色*/\n"
"    border-style: solid;        /*实线*/\n"
"    color: rgb(255, 0, 0);\n"
"    background-color: rgba(255, 0, 0,0.2);    /*按钮背景颜色纯白*/\n"
"}\n"
"\n"
"/**鼠标停留在按钮上的样式**/\n"
"QPushButton::hover{    \n"
"    background-color: rgba(255, 0, 0,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/**鼠标按压下去的样式**/\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.Uninstall.setAutoRepeat(False)
        self.Uninstall.setAutoDefault(False)
        self.Uninstall.setDefault(False)
        self.Uninstall.setFlat(False)
        self.Uninstall.setObjectName("Uninstall")
        self.horizontalLayout_9.addWidget(self.Uninstall)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        self.SettingsScrollArea.setWidget(self.SettingsScrollAreaWidget)
        self.verticalLayout_9.addWidget(self.SettingsScrollArea)
        self.ConsoleWidget = QtWidgets.QTextBrowser(parent=self.Settings)
        self.ConsoleWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(-1)
        self.ConsoleWidget.setFont(font)
        self.ConsoleWidget.setAutoFillBackground(False)
        self.ConsoleWidget.setStyleSheet("/* 主窗口样式 */\n"
"QTextBrowser {\n"
"   background-color: rgb(240, 244, 249);   /*背景色*/   \n"
"   border: 5px solid rgb(240, 244, 249);  /*边框大小、边框样式、边框颜色*/\n"
"   font-size: 20px;                        /* 字体大小 */\n"
"   color: rgb(128, 128, 128);              /*字体颜色为灰色*/\n"
"    border-top-left-radius: 20px;    /* 左上角圆角半径 */\n"
"    border-top-right-radius: 20px;   /* 右上角圆角半径 */\n"
"    background-image: none;\n"
"    padding-top: 20px;        /*调整内部距离*/\n"
"    padding-left: 10px;        /*调整内部距离*/\n"
"    padding-bottom: 0px;    /*调整内部距离*/\n"
"}\n"
"\n"
"/* 滚动条 - 垂直 */\n"
"QTextBrowser QScrollBar:vertical {\n"
"    border-radius:10px;                 /*圆角*/\n"
"    background-color: rgb(240, 244, 249);   /*背景色*/   \n"
"    width: 4px;                         /* 滚动条默认宽度*/\n"
"}\n"
"\n"
"/* 垂直滚动条滑块 */\n"
"QTextBrowser QScrollBar::handle:vertical {\n"
"   border-radius:3px;                   /*圆角*/\n"
"    background-color: rgb(0, 255, 255); /*背景颜色*/\n"
"}\n"
"\n"
"/* 垂直滚动条滑块悬停 */\n"
"QTextBrowser QScrollBar::handle:vertical:hover {\n"
"    background-color: rgba(0, 255, 255,0.5);/*背景颜色*/\n"
"}\n"
"\n"
"/* 滚动条向上、下按钮 */\n"
"QTextBrowser QScrollBar::sub-line:vertical,\n"
"QTextBrowser QScrollBar::add-line:vertical {    \n"
"    height: 0px; /*设置按钮大小为0(不显示)*/\n"
"}\n"
"\n"
"/* 滚动条背景 */\n"
"QTextBrowser QScrollBar::add-page:vertical, \n"
"QTextBrowser QScrollBar::sub-page:vertical {\n"
"    background: none;        /*没有背景,之前是网格*/\n"
"}")
        self.ConsoleWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.ConsoleWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.ConsoleWidget.setReadOnly(False)
        self.ConsoleWidget.setObjectName("ConsoleWidget")
        self.verticalLayout_9.addWidget(self.ConsoleWidget)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/选项卡图标/选项卡图标/用户设置.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ModeWidget.addTab(self.Settings, icon17, "")
        self.verticalLayout.addWidget(self.ModeWidget)

        self.retranslateUi(Arisu)
        self.ModeWidget.setCurrentIndex(0)
        self.StateTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Arisu)

    def retranslateUi(self, Arisu):
        _translate = QtCore.QCoreApplication.translate
        Arisu.setWindowTitle(_translate("Arisu", "Form"))
        self.SoftwareName.setText(_translate("Arisu", "爱丽丝QQ聊天AI 1.0.0"))
        self.hide_btn.setToolTip(_translate("Arisu", "深度隐藏（去任务管理器找）"))
        self.min_system_tray_btn.setToolTip(_translate("Arisu", "隐藏到托盘"))
        self.top_btn.setToolTip(_translate("Arisu", "窗口置顶"))
        self.min_btn.setToolTip(_translate("Arisu", "最小化"))
        self.max_btn.setToolTip(_translate("Arisu", "最大化/恢复"))
        self.close_btn.setToolTip(_translate("Arisu", "关闭"))
        self.Function1.setText(_translate("Arisu", "一键开启"))
        self.Function2.setText(_translate("Arisu", "基础配置"))
        self.Function3.setText(_translate("Arisu", "文档链接"))
        self.Function4.setText(_translate("Arisu", "✨Star"))
        self.ModeWidget.setTabToolTip(self.ModeWidget.indexOf(self.Home), _translate("Arisu", "主页"))
        self.StateScrollAreaTip.setText(_translate("Arisu", "状态监听"))
        self.StateTabWidget.setTabText(self.StateTabWidget.indexOf(self.StateOutput), _translate("Arisu", "状态输出"))
        self.QQGroupName.setPlaceholderText(_translate("Arisu", "请输入Q群名(优先备注名)"))
        self.BotName.setPlaceholderText(_translate("Arisu", "机器人名字(优先群内备注名)"))
        self.Root.setPlaceholderText(_translate("Arisu", "最高权限者(只能有一个)"))
        self.ExitPassword.setPlaceholderText(_translate("Arisu", "退出指令的密码(不能为空)"))
        self.InitRole.setPlaceholderText(_translate("Arisu", "初始人设(不填默认爱丽丝)"))
        self.QQGroupLocation.setPlaceholderText(_translate("Arisu", "Q群窗口的位置(不填默认0,0)"))
        self.RemoveDangerousOrder.setText(_translate("Arisu", "移除危险指令"))
        self.AddOrChangeQQGroup.setText(_translate("Arisu", "添加或修改"))
        self.RemoveQQGroup.setText(_translate("Arisu", "移除Q群"))
        self.SwitchReply.setText(_translate("Arisu", "开启自动回复"))
        self.QQGroupListState.setTitle(_translate("Arisu", "需要回复的QQ群"))
        self.QQGroupList.setSortingEnabled(False)
        self.StateTabWidget.setTabText(self.StateTabWidget.indexOf(self.Bind), _translate("Arisu", "Q群绑定"))
        self.StateTabWidget.setTabToolTip(self.StateTabWidget.indexOf(self.Bind), _translate("Arisu", "QQ群绑定配置录入"))
        self.ModeWidget.setTabToolTip(self.ModeWidget.indexOf(self.StateMonitor), _translate("Arisu", "状态监测"))
        self.KeyboardShortcutLabel.setText(_translate("Arisu", "键盘快捷键"))
        self.KeyboardShortcutTip.setText(_translate("Arisu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">区分：快捷键帮你“快”速操作当前软件，热键让你“热”启动系统或功能（无论在哪）。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">快捷键：任意键盘单键(如 A、B)、鼠标侧键，操作本软件界面时生效，适用长按操作。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">全局热键：仅限组合键 (如 Ctrl+Shift+X) 或 功能键 (如 F12)，软件启动后立即生效，存在长按需求的功能不可用。</span></p></body></html>"))
        self.SwitchReply_5.setText(_translate("Arisu", "文档和项目链接：F1"))
        self.SwitchReply_3.setText(_translate("Arisu", "关闭动态主页：F7"))
        self.SwitchReply_4.setText(_translate("Arisu", "开启动态主页:F8"))
        self.SwitchReply_6.setText(_translate("Arisu", "开启/关闭全屏：F11"))
        self.SwitchReply_2.setText(_translate("Arisu", "开启/关闭爱丽丝的AI自动回复：F12"))
        self.StateScrollAreaTip_2.setText(_translate("Arisu", "开发者功能"))
        self.SwitchReply_7.setText(_translate("Arisu", "开启/关闭重定向窗口(日志窗口)：F9"))
        self.SwitchReply_8.setText(_translate("Arisu", "打开一个cmd窗口(批处理指令)：F10"))
        self.ModeWidget.setTabToolTip(self.ModeWidget.indexOf(self.KeyboardShortcut), _translate("Arisu", "键盘快捷键"))
        self.ModeWidget.setTabToolTip(self.ModeWidget.indexOf(self.QuestionLinks), _translate("Arisu", "问题链接"))
        self.APIKeyState.setToolTip(_translate("Arisu", "API录入状态显示"))
        self.APIKeyInput.setToolTip(_translate("Arisu", "<html><head/><body><p>deepseek的api密钥，如果要更换密钥也是这里输入并确认。</p></body></html>"))
        self.APIKeyInput.setPlaceholderText(_translate("Arisu", "请输入DeepSeek的API密钥(Key)"))
        self.APIKeyConfirm.setToolTip(_translate("Arisu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">1. 什么都不填直接点击确定能测试密钥是否已经存在。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2. 输入密钥点击确定检测密钥是否有效。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">3. 把密钥存储在存储系统密钥库中。</span></p></body></html>"))
        self.APIKeyConfirm.setText(_translate("Arisu", "确认"))
        self.LogicCPUCountState.setToolTip(_translate("Arisu", "API录入状态显示"))
        self.LogicCPUCount.setToolTip(_translate("Arisu", "<html><head/><body><p><span style=\" font-size:11pt; color:#414141;\">输入可使用的逻辑核心数，默认通过编程计算。物理核心数乘上1.5后去掉小数点，如过这个值超过最大逻辑核心数就使用最大逻辑核心数。</span></p></body></html>"))
        self.LogicCPUCount.setPlaceholderText(_translate("Arisu", "请输入运行的最大逻辑核心数"))
        self.LogicCPUCountConfirm.setToolTip(_translate("Arisu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">不懂不要填！</span><span style=\" color:#ff0000;\">不懂不要填！不懂不要填！</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">如果无法获取逻辑核心数，这个值将完全交给用户填写并直接采纳。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">如果能够获取逻辑核心数则会判断用户输入的核心数是否合理，超出后则使用最大逻辑核心数。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">输入可使用的逻辑核心数，默认通过编程计算。物理核心数乘上1.5后去掉小数点，如过这个值超过最大逻辑核心数就使用最大逻辑核心数。</p></body></html>"))
        self.LogicCPUCountConfirm.setText(_translate("Arisu", "确认"))
        self.WinResetTimeState.setToolTip(_translate("Arisu", "API录入状态显示"))
        self.WinResetTime.setToolTip(_translate("Arisu", "<html><head/><body><p><span style=\" font-size:12pt;\">窗口(显示、位置、大小)重置时间，默认设置10秒进行一次保持。</span></p></body></html>"))
        self.WinResetTime.setText(_translate("Arisu", "10"))
        self.WinResetTime.setPlaceholderText(_translate("Arisu", "请输入窗口重置的时间"))
        self.ThreadRestartTimeState.setToolTip(_translate("Arisu", "API录入状态显示"))
        self.ThreadRestartTime.setToolTip(_translate("Arisu", "<html><head/><body><p><span style=\" font-size:12pt;\">窗口绑定失败后等待重新进行绑定的时间。窗口被关闭、被完全遮挡、崩溃就会导致绑定窗口失效。</span></p></body></html>"))
        self.ThreadRestartTime.setText(_translate("Arisu", "10"))
        self.ThreadRestartTime.setPlaceholderText(_translate("Arisu", "请输入线程重启的时间"))
        self.OpenRoleDir.setToolTip(_translate("Arisu", "打开提示库，在这个目录下用户可以自行添加或修改AI自动回复的人设。"))
        self.OpenRoleDir.setText(_translate("Arisu", "人设自定义"))
        self.LogQueryDir.setToolTip(_translate("Arisu", "存放Q群的聊天记录和软件的日志信息"))
        self.LogQueryDir.setText(_translate("Arisu", "日志查询"))
        self.RestoreNavigationBarSortingButton.setText(_translate("Arisu", "还原导航栏排序"))
        self.JMDownloadStrategy.setToolTip(_translate("Arisu", "<html><head/><body><p><span style=\" color:#ff0000;\">不懂不要动！！！</span></p><p>打开禁漫天堂下载策略的配置文件，修改下载策略，默认下载完整的本子。</p></body></html>"))
        self.JMDownloadStrategy.setText(_translate("Arisu", "禁漫天堂下载策略"))
        self.InitialInterfaceLocationComboBox.setToolTip(_translate("Arisu", "初始界面位置"))
        self.InitialInterfaceLocationComboBox.setCurrentText(_translate("Arisu", "主页"))
        self.InitialInterfaceLocationComboBox.setItemText(0, _translate("Arisu", "主页"))
        self.InitialInterfaceLocationComboBox.setItemText(1, _translate("Arisu", "状态监测"))
        self.InitialInterfaceLocationComboBox.setItemText(2, _translate("Arisu", "键盘热键"))
        self.InitialInterfaceLocationComboBox.setItemText(3, _translate("Arisu", "问题链接"))
        self.InitialInterfaceLocationComboBox.setItemText(4, _translate("Arisu", "用户设置"))
        self.KeywordReplyDir.setToolTip(_translate("Arisu", "打开关键词回复目录，在这个目录下用户可以自行添加或修改AI自动回复的规则。"))
        self.KeywordReplyDir.setText(_translate("Arisu", "关键词回复"))
        self.Uninstall.setToolTip(_translate("Arisu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">没有挽留，只为尊重你的选择!卸载软件本体、回收资源和清除软件产生的文件，做到绝不留下任何一点垃圾。</p></body></html>"))
        self.Uninstall.setText(_translate("Arisu", "一键卸载"))
        self.ModeWidget.setTabToolTip(self.ModeWidget.indexOf(self.Settings), _translate("Arisu", "用户设置"))
from PyQt6.QtMultimediaWidgets import QVideoWidget
